import { MigrationInterface, QueryRunner } from "typeorm";

export class MigrateStudios1780318187691 implements MigrationInterface {
    name = 'MigrateStudios1780318187691'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            CREATE TABLE IF NOT EXISTS "studios" (
                "id" integer PRIMARY KEY,
                "name" varchar(256) NOT NULL
            )
        `);

        await queryRunner.query(`
            INSERT INTO "studios" ("id", "name") VALUES
            (1, 'Studio Pierrot'),
            (2, 'Kyoto Animation'),
            (3, 'Gonzo'),
            (4, 'Bones'),
            (5, 'Bee Train'),
            (6, 'Gainax'),
            (7, 'J.C.Staff'),
            (8, 'Artland'),
            (10, 'Production I.G'),
            (11, 'Madhouse'),
            (13, 'Studio 4°C'),
            (14, 'Sunrise'),
            (15, 'Sony Pictures Entertainment'),
            (16, 'TV Tokyo'),
            (17, 'Aniplex'),
            (18, 'Toei Animation'),
            (21, 'Studio Ghibli'),
            (22, 'Nippon Animation'),
            (23, 'Bandai Visual'),
            (24, 'Studio Fantasia'),
            (25, 'Milky Animation Label'),
            (26, 'Shinkai Makoto'),
            (27, 'Xebec'),
            (28, 'OLM'),
            (29, 'VAP'),
            (30, 'Ajia-do'),
            (31, 'Geneon Universal Entertainment'),
            (32, 'Manglobe'),
            (33, 'WOWOW'),
            (34, 'HAL Film Maker'),
            (35, 'Seven Arcs'),
            (36, 'Gallop'),
            (37, 'Studio Deen'),
            (38, 'Arms'),
            (39, 'Daume'),
            (40, 'm.o.e.'),
            (41, 'Satelight'),
            (42, 'GDH'),
            (43, 'ufotable'),
            (44, 'Shaft'),
            (45, 'Pink Pineapple'),
            (47, 'Khara'),
            (48, 'AIC'),
            (49, 'Remic'),
            (50, 'KSS'),
            (51, 'Diomedéa'),
            (52, 'Avex Entertainment'),
            (53, 'Dentsu Inc.'),
            (54, 'Mook Animation'),
            (55, 'TV Asahi'),
            (56, 'A-1 Pictures'),
            (58, 'Square Enix'),
            (59, 'Beat Frog'),
            (60, 'Actas'),
            (61, 'Frontier Works'),
            (62, 'Shogakukan-Shueisha Productions'),
            (63, 'Trinet Entertainment'),
            (64, 'Sotsu'),
            (65, 'Tokyo Movie Shinsha'),
            (66, 'Key'),
            (67, 'OB Planning'),
            (68, 'Mushi Production'),
            (69, 'Front Line'),
            (70, 'Nomad'),
            (71, 'Mellow Head'),
            (72, 'Artmic'),
            (73, 'TMS Entertainment'),
            (75, 'Imagin'),
            (76, 'Yomiuri Telecasting Corporation'),
            (77, 'APPP'),
            (78, 'Picture Magic'),
            (79, 'Genco'),
            (80, 'Trans Arts'),
            (81, 'Radix'),
            (82, 'Marvelous Entertainment'),
            (83, 'AIC Spirits'),
            (84, 'Studio Rikka'),
            (85, 'Konami'),
            (86, 'Group TAC'),
            (88, 'AIC ASTA'),
            (89, 'BeSTACK'),
            (91, 'feel.'),
            (92, 'Starchild Records'),
            (93, 'Studio Flag'),
            (94, 'Telecom Animation Film'),
            (95, 'Doga Kobo'),
            (96, 'Yumeta Company'),
            (97, 'ADV Films'),
            (98, 'Sav! The World Productions'),
            (99, 'Kitty Films'),
            (100, 'TV Osaka'),
            (101, 'Studio Hibari'),
            (102, 'FUNimation Entertainment'),
            (103, 'Tatsunoko Production'),
            (104, 'Lantis'),
            (107, 'Plum'),
            (108, 'Media Factory'),
            (109, 'Shochiku'),
            (110, 'Triangle Staff'),
            (111, 'NHK'),
            (112, 'Brain''s Base'),
            (113, 'Kadokawa Shoten'),
            (114, 'Studio Matrix'),
            (116, 'Broccoli'),
            (117, 'Studio Izena'),
            (118, 'SynergySP'),
            (119, 'Viz Media'),
            (120, 'TNK'),
            (121, 'Active'),
            (122, 'Tokyo Kids'),
            (123, 'Victor Entertainment'),
            (124, 'Animac'),
            (125, 'Pioneer Entertainment (USA)'),
            (126, 'Studio Comet'),
            (127, 'Yomiko Advertising'),
            (129, 'Silky’ s'),
            (130, 'CherryLips'),
            (131, 'G&G Entertainment'),
            (132, 'P.A. Works'),
            (133, 'Shinyusha'),
            (134, 'HoriPro'),
            (135, 'MediaNet'),
            (136, 'Vega Entertainment'),
            (137, 'PPM'),
            (138, 'Himajin Planning'),
            (139, 'Nihon Ad Systems'),
            (140, 'Animax'),
            (141, 'Toei Video'),
            (142, 'Asatsu DK'),
            (143, 'Mainichi Broadcasting'),
            (144, 'Pony Canyon'),
            (145, 'TBS'),
            (146, 'CBC'),
            (147, 'SKY Perfect Well Think'),
            (148, 'Hakunensha'),
            (149, 'SME Visual Works'),
            (150, 'Sanrio'),
            (152, 'Green Bunny'),
            (153, 'SoftX'),
            (154, 'E&G Films'),
            (155, 'animate Film'),
            (156, 'Polygram Japan'),
            (157, 'BMG Japan'),
            (158, 'KIDS STATION'),
            (159, 'Kodansha'),
            (160, 'Rondo Robe'),
            (161, 'Sogo Vision'),
            (162, 'Character and Anime Dot Com'),
            (163, 'asread.'),
            (164, 'd-rights'),
            (165, 'Marubeni'),
            (166, 'Movic'),
            (167, 'Sega'),
            (168, 'Shelty'),
            (169, 'Fuji TV'),
            (170, 'Imagica'),
            (171, 'A-Line'),
            (172, 'Alchemist'),
            (173, 'Alice Soft'),
            (175, 'Planet'),
            (176, 'Ginga Ya'),
            (177, 'Studio Kyuuma'),
            (178, 'Trilogy Future Studio'),
            (179, 'A.C.G.T.'),
            (182, 'Age'),
            (183, 'Agent 21'),
            (184, 'Ai ga areba Daijobu'),
            (185, 'Aiko'),
            (186, 'Ail'),
            (189, 'GEN Productions'),
            (190, 'RCC Chugoku Broadcasting'),
            (191, 'Eiken'),
            (192, 'Shinkuukan'),
            (193, 'Idea Factory'),
            (194, 'ANIK'),
            (195, 'Pixy'),
            (196, 'Production Reed'),
            (197, 'Studio Junior'),
            (198, 'Gakken'),
            (199, 'Studio Nue'),
            (200, 'Tezuka Productions'),
            (203, 'Visual Art’s'),
            (204, 'PIONEER LDC'),
            (205, 'Nihon Ad Systems'),
            (206, 'Digital Works'),
            (207, 'Magic Bus'),
            (208, 'Three Fat Samurai'),
            (209, 'Sol Blade'),
            (210, 'Studio Tulip'),
            (211, 'Rakuonsha'),
            (212, 'Venus Vangard'),
            (213, 'Half H.P Studio'),
            (214, 'BS-i'),
            (215, 'Nelvana'),
            (216, 'Studio Tron'),
            (217, 'The Right Stuf International'),
            (218, 'Zexcs'),
            (220, 'Youmex'),
            (222, 'Jade Animation'),
            (224, 'Toshiba EMI'),
            (226, 'Panmedia'),
            (228, 'Daewon Media'),
            (229, 'The Answer Studio'),
            (230, 'Bandai'),
            (231, 'CyberConnect2'),
            (233, 'Bandai Entertainment'),
            (234, 'Oh! Production'),
            (235, 'Shirogumi'),
            (236, 'YTV'),
            (238, 'AT-X'),
            (239, 'Y.O.U.C'),
            (240, 'Capcom'),
            (241, 'KOEI'),
            (242, 'Ashi Productions'),
            (244, 'D3'),
            (245, 'Toho'),
            (246, 'Visual 80'),
            (247, 'Shin-Ei Animation'),
            (248, 'Tin House'),
            (249, 'Robot Communications'),
            (250, 'Media Blasters'),
            (252, '4Kids Entertainment'),
            (253, 'Rikuentai'),
            (254, 'Soft Garage'),
            (255, 'Imagi'),
            (256, 'Studio Kikan'),
            (257, 'Jam'),
            (258, 'Echo'),
            (259, 'Kaeruotoko Shokai'),
            (260, 'Shuuhei Morita'),
            (261, 'San-X'),
            (262, 'Kadokawa Pictures USA'),
            (265, 'Valkyria'),
            (266, 'Natural High'),
            (267, 'Five Ways'),
            (268, 'Hot Bear'),
            (269, 'DiC Entertainment'),
            (270, 'NuTech Digital'),
            (271, 'Barnum Studio'),
            (272, 'Studio Kajino'),
            (273, 'Think Corporation'),
            (274, 'Suzuki Mirano'),
            (275, 'Kojiro Shishido Animation Works'),
            (276, 'DLE'),
            (277, 'Anime Midstream'),
            (278, 'Daiei Film Co. Ltd.'),
            (279, 'Skouras'),
            (280, 'Studio Junio'),
            (281, 'Kokusai Eigasha'),
            (282, 'Gentosha Comics'),
            (283, 'KENMedia'),
            (284, 'Central Park Media'),
            (285, 'Four Some'),
            (287, 'David Production'),
            (288, 'Kaname Productions'),
            (289, 'ACiD FiLM'),
            (290, 'Kinema Citrus'),
            (291, 'CoMix Wave Films'),
            (292, 'AIC PLUS+'),
            (293, 'Picograph'),
            (294, 'Discovery'),
            (295, 'BaseSon'),
            (296, 'Critical Mass'),
            (297, 'Armor'),
            (298, 'Anima'),
            (299, 'Studio Pastoral'),
            (300, 'SILVER LINK.'),
            (301, 'Langmaor'),
            (302, 'GODxDOG Production '),
            (304, 'Primastea'),
            (306, 'Magic Capsule'),
            (307, 'Sunwoo Entertainment'),
            (308, 'Yellow Film'),
            (309, 'GoHands'),
            (310, 'Animeigo'),
            (311, 'Enoki Films'),
            (312, 'Life Work'),
            (313, 'Omnibus Japan'),
            (314, 'White Fox'),
            (315, 'DAX Production'),
            (316, 'Nippon Shuppan Hanbai (Nippan) K.K.'),
            (317, 'NHK Enterprises'),
            (318, 'WAO World'),
            (319, 'MS Pictures'),
            (320, 'Maru Production '),
            (321, 'Kitty Media'),
            (322, 'Bee Media'),
            (323, 'Nippon Columbia'),
            (324, 'Directions'),
            (325, 'Code'),
            (326, 'Animation 21'),
            (327, 'Takara'),
            (328, 'Casio Entertainment'),
            (329, 'Phoenix Entertainment'),
            (330, 'Kanaban Graphics'),
            (331, 'Indeprox'),
            (332, 'Takeshobo'),
            (333, 'TYO Animations'),
            (334, 'Ordet'),
            (335, 'Seta Corporation'),
            (336, 'JM Animation'),
            (338, 'Studio Bogey'),
            (339, 'Rankin/Bass'),
            (340, 'Future Planet'),
            (341, 'SamBakZa'),
            (342, 'Japan Home Video'),
            (343, 'Puzzle Animation Studio Limited'),
            (344, 'ATLUS'),
            (345, 'TAKI Corporation'),
            (346, 'Hoods Entertainment'),
            (347, 'PrimeTime'),
            (348, 'Kawamoto Productions Ltd.'),
            (349, 'Itasca Studio'),
            (350, 'The Village of Marchen'),
            (351, 'Big West'),
            (352, 'Kadokawa Pictures Japan'),
            (353, 'Chungeorahm Film'),
            (354, 'Encourage Films'),
            (356, 'Cranberry'),
            (357, 'Innocent Grey'),
            (358, 'Telescreen'),
            (359, 'NHK-BS2'),
            (361, 'Oxybot'),
            (362, 'Film Workshop'),
            (363, 'Topcraft'),
            (364, 'Sovat Theater'),
            (365, 'PoRO'),
            (366, 'Tomoyasu Murata Company'),
            (367, 'Heewon Entertainment'),
            (368, 'UM Productions'),
            (370, 'Iyasakadou Film'),
            (371, 'Union Cho'),
            (373, 'Panda Factory'),
            (374, 'Plus Heads'),
            (375, 'I.Toon'),
            (376, 'Sentai Filmworks'),
            (377, 'Kuri Jikken Manga Koubou'),
            (378, 'Grasshoppa!'),
            (379, 'Avaco Creative Studios'),
            (380, 'Amuse Pictures'),
            (381, 'Yamato Works'),
            (382, 'Tokuma Shoten'),
            (383, 'KMMJ Studios'),
            (384, 'Trick Block'),
            (385, 'Tele-Cartoon Japan'),
            (386, 'Animaruya'),
            (387, 'Blue Eyes'),
            (388, 'Tamura Shigeru Studio'),
            (389, 'I-move'),
            (390, 'Tsuchida Productions'),
            (391, 'Grouper Productions'),
            (392, 'Enterbrain'),
            (393, 'Epoch'),
            (394, 'Misseri Studio'),
            (395, 'Oz Inc.'),
            (396, 'Asia-Do'),
            (397, 'Bridge'),
            (398, 'Milky Cartoon'),
            (399, 'Dream Force'),
            (400, 'Gathering'),
            (401, 'ChuChu'),
            (402, 'ChiChinoya'),
            (403, 'Tokyo Media Connections'),
            (404, 'Studio Unicorn'),
            (405, 'T-Rex'),
            (406, 'Asahi Production'),
            (407, 'Studio 9 Maiami'),
            (408, 'Amino'),
            (409, 'Studio Egg'),
            (410, 'Adult Source Media'),
            (411, 'KBS'),
            (412, 'Studio Wombat'),
            (413, 'Pastel'),
            (414, 'Lemon Heart'),
            (415, 'Warner Bros.'),
            (416, 'TAP'),
            (417, 'Walt Disney Studios'),
            (418, 'Studio Gokumi'),
            (419, 'ElectromagneticWave'),
            (420, 'ACC Production'),
            (421, 'International Digital Artist Inc.'),
            (422, 'Schoolzone'),
            (423, 'Studio Eromatick'),
            (424, 'Mary Jane'),
            (425, 'AIC Takarazuka'),
            (426, 'Filmlink International'),
            (427, 'Studio G-1Neo'),
            (428, 'Nichiei Agency'),
            (429, 'Office AO'),
            (430, 'Mad Box'),
            (431, 'Procidis'),
            (432, 'Kachidoki Studio'),
            (433, 'Viewworks'),
            (434, 'Synergy Japan'),
            (435, 'Studio Zero'),
            (436, 'AIC Build'),
            (437, 'Kamikaze Douga'),
            (438, 'Studio Signal'),
            (439, 'Project No.9'),
            (440, 'Studio Kuma'),
            (441, '8bit'),
            (442, 'Minami Machi Bugyousho'),
            (443, 'Studio PuYUKAI'),
            (444, 'Jinnis Animation Studios'),
            (445, 'Bliss Pictures'),
            (446, 'RTHK'),
            (447, 'Hero Communication'),
            (448, 'Postgal Workshop'),
            (449, 'Maikaze'),
            (450, 'Wako Production'),
            (451, 'Cookie Jar Entertainment'),
            (452, 'Knack Productions'),
            (453, 'Tsuburaya Productions'),
            (455, 'Palm Studio'),
            (456, 'Lerche'),
            (457, 'Venet'),
            (458, 'Beijing Sharaku Art Co.'),
            (459, 'Nitroplus'),
            (460, 'The Klock Worx'),
            (461, 'OLE-M'),
            (462, 'Chaos Project'),
            (463, 'M.S.C'),
            (464, 'flying DOG'),
            (465, 'Hasbro'),
            (466, 'Digital Media Lab'),
            (467, 'Discotek'),
            (468, 'Nihon Falcom'),
            (469, 'ING'),
            (470, 'GAGA Communications'),
            (471, 'Shanghai Animation Film Studio'),
            (472, 'Usagi Ou'),
            (473, 'Ascension'),
            (474, 'Shogakukan Music & Digital Entertainment'),
            (475, 'Ishikawa Pro'),
            (476, 'The Berich'),
            (477, 'Kino Production'),
            (478, 'Studio Blanc.'),
            (479, 'DOGA Productions'),
            (480, 'Tokyo TV'),
            (481, 'Office Take Off'),
            (482, 'Automatic Flowers Studio'),
            (483, 'Marvel Entertainment'),
            (484, 'TOKYOPOP'),
            (485, 'Shinwon Productions'),
            (486, 'Digital Frontier'),
            (487, 'Studio MWP'),
            (488, 'Anchor Bay Films'),
            (489, 'TCJ'),
            (490, 'Maiden Japan'),
            (491, 'Byakuya Shobo'),
            (492, 'Horannabi'),
            (493, 'Aniplex of America'),
            (494, 'Studio Take Off'),
            (495, 'Moonstone Cherry'),
            (497, 'Studio Gram'),
            (499, 'The Pokemon Company International'),
            (501, 'Miramax Films'),
            (505, 'Nintendo of America'),
            (507, 'Universal Studios'),
            (509, 'Fuji Video'),
            (511, 'Wonder Kids'),
            (513, 'Nikkatsu'),
            (515, 'Fairy Dust'),
            (517, 'Asmik Ace'),
            (519, 'Collaboration Works'),
            (521, 'Anpro'),
            (523, 'SBS TV Production'),
            (525, 'KAGAYA Studio'),
            (527, 'Higa Brothers Production'),
            (529, 'Lapis'),
            (531, 'Elevenarts'),
            (533, 'N&G Production'),
            (535, 'Knack Animation'),
            (537, 'SANZIGEN'),
            (539, 'Ultra Super Pictures'),
            (541, 'Seven'),
            (543, 'Studio Saki Makura'),
            (545, 'Studio Deva Loka'),
            (547, 'Hobby Japan'),
            (549, 'StudioRF Inc.'),
            (551, 'Crossphere'),
            (553, 'Marvy Jack'),
            (555, 'Studio Chizu'),
            (557, 'Zyc'),
            (559, 'Purple Cow Studio Japan'),
            (561, 'U/M/A/A Inc.'),
            (563, 'LandQ studios'),
            (565, 'LMD'),
            (567, 'D.A.S.T Corporation'),
            (569, 'MAPPA'),
            (571, 'Obtain Future'),
            (573, 'JapanAnime'),
            (575, 'Katsudou-manga-kan'),
            (577, 'Tohokushinsha Film Corporation'),
            (579, 'AT-2'),
            (581, 'Sparky Animation'),
            (583, 'Annapuru'),
            (585, 'Arplants'),
            (587, 'Tomason'),
            (589, 'Academy Productions'),
            (591, 'Romanov Films'),
            (593, 'Egg'),
            (595, 'NYAV Post'),
            (601, 'lxtl'),
            (603, 'CLOCKUP'),
            (605, 'C2C'),
            (607, 'RAMS'),
            (609, 'Cammot'),
            (611, 'Sakura Production'),
            (613, 'Jormungand Production Partners'),
            (615, 'Dream Creation'),
            (617, 'Azumanga Daioh Production Committee'),
            (619, 'Cospa'),
            (621, 'SoftBank Creative Corp.'),
            (623, 'Kimi To Boku Production Partners'),
            (625, 'H.O.T.D Production Committee'),
            (627, 'Madoka Partners'),
            (629, 'Studio Sign'),
            (631, 'Acchi Kocchi Production Committee'),
            (633, 'Tasogare Otome×Amnesia Production Partners'),
            (635, 'Saki Achiga-hen Production Committee'),
            (637, 'Möbius Tone'),
            (639, 'Hiiro No Kakera Production Committee'),
            (641, 'Japan Aerospace Exploration Agency'),
            (643, 'Trinity Sound'),
            (645, 'Audio Highs'),
            (647, 'Memory-Tech'),
            (649, 'Hanokiwa Academy Student Council'),
            (651, 'Sengoku Collection Production Committee'),
            (653, 'tsuritama partners'),
            (655, 'Volks'),
            (657, 'Lucky Paradise'),
            (659, 'AKB0048 Production Committee'),
            (661, 'Right Gauge'),
            (663, 'Dwango Music Entertainment'),
            (665, 'chara-ani.com'),
            (667, 'AC Create'),
            (669, 'My Melody Production Committee'),
            (675, 'Yomiuri Advertising'),
            (677, 'Nexon'),
            (679, 'Soyuzmultfilm'),
            (681, 'ASCII Media Works'),
            (683, 'Astarotte no Omocha! Production Committee'),
            (685, 'Kadokawa Contents Gate'),
            (687, 'Bandai Namco Live Creative'),
            (689, 'NTT Docomo'),
            (691, '501st JOINT FIGHTER WING'),
            (693, 'BS-TBS'),
            (695, 'Sankarea Production Committee'),
            (697, 'Natsuiro Kiseki Production Partners'),
            (699, 'feng'),
            (701, 'seikaisha'),
            (703, 'Notes'),
            (705, 'Project Railgun'),
            (707, 'TMS-Kyokuchi'),
            (709, 'PPP'),
            (711, 'Delphi Sound'),
            (713, '12 Diary Holders'),
            (715, 'Dwango'),
            (717, 'TV Tokyo Music'),
            (719, 'Studio Mausu'),
            (721, 'GANSIS'),
            (723, 'Hotline'),
            (725, 'Hatsukoi Limited Production Committee'),
            (727, 'Kiyosumi High School Mahjong Club'),
            (729, 'Raku High Student Council'),
            (731, 'Inu x Boku SS Production Partners'),
            (733, 'Viki'),
            (735, 'Slowcurve'),
            (737, 'Sony Music Communications'),
            (739, 'Project IS'),
            (741, 'Toshiba Entertainment'),
            (743, 'Project Eureka AO'),
            (745, 'Cosmic Ray'),
            (747, 'Apollon'),
            (749, 'Pony Canyon Enterprises'),
            (751, 'Marvelous AQL'),
            (753, 'PRA'),
            (755, 'Jumondou'),
            (757, 'Sony Music Entertainment'),
            (759, 'Eye Move'),
            (761, 'Sunny Side Up'),
            (763, 'Miracle Robo'),
            (765, 'Sakura Create'),
            (767, 'Majin'),
            (769, 'Fuji Pacific Music Publishing'),
            (771, 'Kyokuichi Tokyo Movie Shinsha'),
            (773, 'Peter Pan Creation'),
            (775, 'Bushiroad Inc.'),
            (777, 'Showgate'),
            (779, 'AMG MUSIC'),
            (781, 'Studio NOA'),
            (783, 'GKids'),
            (785, 'Advance Syakujii'),
            (787, 'Happinet Pictures'),
            (789, 'BIGLOBE'),
            (791, 'Dentsu Entertainment USA'),
            (793, 'Glams'),
            (795, 'Yahoo! Japan'),
            (797, 'Hobunsha'),
            (799, 'indigo line'),
            (801, 'Nihikime no Dozeu'),
            (803, 'Trigger'),
            (805, 'AIC Frontier'),
            (807, 'Po10tial'),
            (809, 'AKOM'),
            (811, 'Hang Zhou StarQ'),
            (813, 'SoftCel Pictures'),
            (815, 'EMI'),
            (817, 'WField'),
            (819, 'Next Media Animation'),
            (821, 'Cotton Doll'),
            (823, 'Lune Pictures'),
            (825, 'Fifth Avenue'),
            (827, 'Amber Film Works'),
            (829, 'Studio Jack'),
            (831, 'Otogi Production'),
            (833, 'Kyotoma'),
            (835, 'UNLIMITED Partners'),
            (837, 'Saki Zenkoku-hen Production Committee'),
            (839, 'LIDENFILMS'),
            (841, 'Saban Entertainment'),
            (843, 'BS Fuji'),
            (845, 'Project No Name'),
            (847, 'Senran Kagura Partners'),
            (848, 'Kazami Gakuen Koushiki Douga-bu'),
            (850, 'Kenji Studio'),
            (852, 'Nexus'),
            (854, 'Solid Vox'),
            (856, 'Charaction'),
            (858, 'Wit Studio'),
            (860, 'Triple X'),
            (862, 'Pashmina'),
            (866, 'Fanworks'),
            (868, 'Devil Survivor 2 Animation Committee'),
            (870, 'Index'),
            (872, 'Shingeki no Kyojin Team'),
            (874, 'Flex Comics'),
            (876, 'G-mode'),
            (878, 'An DerCen'),
            (880, 'gimik'),
            (882, 'Toranoana'),
            (884, 'Strawberry Meets Pictures'),
            (886, 'Cinema Tohoku'),
            (890, 'Karaku'),
            (892, 'NOTTV'),
            (894, 'Graphinica'),
            (896, 'Larx Entertainment'),
            (898, 'I.Gzwei'),
            (899, 'Tokyo Animation Film'),
            (901, 'Tsubasa Entertainment'),
            (903, 'Studio Zealot'),
            (905, 'Tokuma Japan'),
            (907, 'AYCO'),
            (909, 'Studio Kelmadick'),
            (911, 'Passione'),
            (913, 'Ryukyu Asahi Broadcasting'),
            (917, 'Takahashi Studio'),
            (919, 'Ankama'),
            (921, 'Dynamic Planning'),
            (923, 'CyberStep'),
            (925, 'Earth Star Entertainment'),
            (927, 'Dibetagurashi Production Committee'),
            (929, 'Animation Do'),
            (931, 'Poncotan'),
            (933, 'Carp Studio'),
            (935, 'NHK-BS1'),
            (937, 'Studio Kaab'),
            (939, 'Tama Production'),
            (941, 'Iwatobi High School Swimming Club'),
            (943, 'Koichi Kikuchi'),
            (945, 'Vasoon Animation'),
            (947, 'Manga Entertainment'),
            (949, 'teamKG'),
            (951, 'NAZ'),
            (953, 'Soft on Demand'),
            (955, 'Watamote Production Committee'),
            (957, 'Connect'),
            (959, 'Studio Compile'),
            (961, 'Baramiri'),
            (963, 'Mages'),
            (965, 'Crimson Star Media'),
            (967, 'Pupa Production Committee'),
            (969, 'Uchouten Kazoku Production Committee'),
            (971, 'Anime R'),
            (973, 'Studio Liberty'),
            (975, 'Angelfish'),
            (977, 'Queen Bee'),
            (979, 'SPEED'),
            (981, 'BOOTLEG'),
            (983, 'Daiko'),
            (985, 'P Productions'),
            (987, 'Creative Bridge'),
            (989, 'Nihon Hoso Eigasha'),
            (991, 'Hoso Seisaku Doga'),
            (993, 'Tesagure! Production Committee'),
            (995, 'Coamix'),
            (997, 'Maxell E-Cube'),
            (999, 'Studio Animal'),
            (1001, 'Kyodo Eiga'),
            (1003, 'Nippon Television Network Corporation'),
            (1005, 'Oddjob'),
            (1009, 'Aubeck'),
            (1011, 'Warner Music Japan'),
            (1013, 'Opera House'),
            (1015, 'T.O Entertainment'),
            (1017, 'Liverpool'),
            (1019, 'Himeyuri Alumnae Incorporated Foundation'),
            (1021, 'ASIA Documentary Productions'),
            (1023, 'Polygon Pictures'),
            (1025, 'Dongwoo A&E'),
            (1027, 'Milkshake'),
            (1029, 'BeeWorks'),
            (1031, 'Universal Radio Studio'),
            (1033, 'Studio Colorido'),
            (1035, 'Mikakunin de Shinkoukei Production Committee'),
            (1037, 'Japan Vistec'),
            (1039, 'DIVE II Entertainment'),
            (1041, 'Ai Addiction'),
            (1043, 'Benesse Corporation'),
            (1045, 'Space Neko Company'),
            (1047, 'ZIZ'),
            (1049, 'PoPoCo'),
            (1053, 'Production IMS'),
            (1055, 'Yamamura Animation'),
            (1057, 'Kyowa Film'),
            (1059, 'Studio Nem'),
            (1061, 'Project Team Eikyuu Kikan'),
            (1063, 'CALF'),
            (1065, 'Public & Basic'),
            (1067, 'Rising Force'),
            (1071, 'Studio Lotus'),
            (1073, 'Magic Lantern Film'),
            (1075, 'C-Station'),
            (1077, 'MMDGP'),
            (1079, '3xCube'),
            (1081, 'ZERO-A'),
            (1083, 'Aikikaku Center'),
            (1085, 'Cosmos'),
            (1087, 'Lay-duce'),
            (1089, 'Studio Zain'),
            (1091, 'Gakken Eigakyoku'),
            (1093, 'BreakBottle'),
            (1095, 'Studio Cockpit'),
            (1097, 'Namco Bandai Games'),
            (1099, 'Cyclone Graphics'),
            (1101, 'Lambert'),
            (1103, 'TROYCA'),
            (1105, 'Gendai Production'),
            (1107, 'Rabbit Gate'),
            (1109, 'Orange'),
            (1111, 'DandeLion Animation Studio'),
            (1113, 'NBCUniversal Entertainment'),
            (1115, 'Studio Korumi'),
            (1117, '1st PLACE'),
            (1119, 'Shuka'),
            (1121, 'Banpresto'),
            (1123, 'Lucent Pictures Entertainment'),
            (1125, 'Tsubu Doll Production Committee'),
            (1127, 'Studio 3Hz'),
            (1129, 'Pierrot Plus'),
            (1131, 'Zero-G Room'),
            (1133, 'dwarf'),
            (1135, 'FOREST Hunting One'),
            (1137, 'SEK Studios'),
            (1139, 'BEAM Entertainment'),
            (1143, 'TOHO animation'),
            (1147, 'Shinano Kikaku'),
            (1149, 'Studio Cab'),
            (1151, 'Sanrio Digital'),
            (1153, 'Image Kei'),
            (1155, 'Studio Moriken'),
            (1157, 'Big Bang'),
            (1159, 'King Bee'),
            (1161, 'Allure'),
            (1163, 'Flatiron Film Company'),
            (1165, 'Tri-Slash'),
            (1167, 'Nikkatsu Mukojima'),
            (1169, 'ILCA'),
            (1171, 'Olive Studio'),
            (1173, 'Studio Dadashow'),
            (1175, 'Atelier Musa'),
            (1177, ' Geijutsu Eigasha'),
            (1179, 'MK Pictures'),
            (1181, 'RG Animation Studios'),
            (1183, 'E&G Films'),
            (1185, '81 Produce'),
            (1187, 'Ripple Film'),
            (1189, 'Sola Digital Arts'),
            (1191, 'Azeta Pictures'),
            (1193, 'MooGoo'),
            (1195, 'Creators in Pack'),
            (1197, 'Steve N'' Steven'),
            (1199, 'L.'),
            (1201, 'Ponycan USA'),
            (1203, 'Studio 1st'),
            (1205, 'Answer Studio'),
            (1207, 'Comic Umenohone'),
            (1209, 'Studio A-CAT'),
            (1211, 'Tokyo MX'),
            (1213, 'Mobcast'),
            (1215, 'Daiichi Kosho Co.'),
            (1217, 'HeART-BIT'),
            (1223, 'Teichiku Entertainment'),
            (1225, 'Age Global Networks'),
            (1227, 'Studio GDW'),
            (1229, 'Pie in the sky'),
            (1231, 'OLM Digital'),
            (1233, 'Bandai Namco Games'),
            (1235, 'I was a Ballerina'),
            (1237, 'Millepensee'),
            (1239, 'KeyEast'),
            (1241, 'Evil Line Records'),
            (1242, 'Sakura Color Film'),
            (1243, 'AniMan'),
            (1244, 'Studio VOLN'),
            (1245, 'ZIZ Entertainment (ZIZ)'),
            (1246, 'AIR AGENCY'),
            (1247, 'Mistral Japan'),
            (1248, 'Mirai Fusion'),
            (1249, 'Mirai Film'),
            (1250, 'The National Film Center Japan'),
            (1251, 'Dentsu Eigasha Tokyo'),
            (1252, 'Studio Binzo'),
            (1253, 'Studio GOONEYS'),
            (1254, 'Grooove'),
            (1255, 'Glovision'),
            (1256, 'Harappa'),
            (1257, 'A-Real'),
            (1258, 'Bandai Namco Pictures'),
            (1259, 'Studio Curtain'),
            (1260, 'Nakamura Production'),
            (1261, 'Good Smile Company'),
            (1263, 'Dynamo Pictures'),
            (1264, 'EMT Squared'),
            (1265, 'Tomovies'),
            (1266, 'Studio! Cucuri'),
            (1267, 'Tencent Comic'),
            (1268, 'L²Studio'),
            (1269, 'K-Factory'),
            (1270, 'Sanctuary'),
            (1271, 'Assez Finaud Fabric'),
            (1273, 'Osaka University of Arts'),
            (1276, 'HS Pictures Studio'),
            (1277, 'Imagica West'),
            (1278, 'Signal.MD'),
            (1279, 'Buemon'),
            (1280, 'Media Castle'),
            (1281, 'Office DCI'),
            (1282, 'Arcturus'),
            (1283, 'TC Entertainment'),
            (1284, 'Avex Pictures'),
            (1285, 'Being'),
            (1286, '10Gauge'),
            (1287, 'Q-Tec'),
            (1288, 'Chrono Gear Creative'),
            (1289, 'F.M.F'),
            (1290, 'Pollyanna Graphics'),
            (1291, 'KOO-KI'),
            (1292, 'TUBA'),
            (1293, 'Romantica club !! '),
            (1294, 'Studio Don Juan'),
            (1295, 'PINE JAM'),
            (1296, 'Marza Animation Planet'),
            (1298, 'Sakura Motion Picture'),
            (1299, 'AXsiZ'),
            (1300, 'Office Nobu'),
            (1301, 'CCTV Animation Group'),
            (1302, 'RoiVisual'),
            (1303, 'PansonWorks'),
            (1304, 'Qualia Animation'),
            (1305, 'Milestone Music Publishing'),
            (1306, 'AIC Classic'),
            (1313, 'Amuse'),
            (1314, 'Gaina'),
            (1317, 'Production GoodBook'),
            (1320, 'Joker Films'),
            (1321, 'Haoliners Animation'),
            (1322, 'Creative Power Entertaining'),
            (1324, 'Shimogumi'),
            (1325, 'Haoliners Animation'),
            (1328, 'Decovocal'),
            (1340, 'Typhoon Graphics'),
            (1348, 'Sugar Boy'),
            (1349, 'Tencent Animation & Comics'),
            (1350, 'B.CMAY PICTURES'),
            (1351, 'EDGE'),
            (1352, 'Studio Ten Carat'),
            (1353, 'Issen'),
            (1356, 'Tonko House'),
            (1357, 'Craftar Studios'),
            (1360, 'Hoods Drifters Studio'),
            (1361, 'Darts'),
            (1362, 'Rabbit Machine'),
            (1363, 'Marine Entertainment'),
            (1365, 'Shueisha'),
            (1368, 'Kazuki Production'),
            (1369, 'G-Lam'),
            (1370, 'Sprite Animation Studios'),
            (1371, 'T.P.O'),
            (1372, 'Soeishinsha'),
            (1374, 'Office TakeOut'),
            (1375, 'Studio Jam'),
            (1379, 'Zero-G'),
            (1380, 'domerica'),
            (1381, 'GEMBA'),
            (1382, 'Piko Studio'),
            (1383, 'Studio Live'),
            (1384, 'CinePix'),
            (1385, 'Blue Cat'),
            (1387, 'Neft Film'),
            (1393, 'Geno Studio'),
            (1396, 'W-Toon Studio'),
            (1399, 'asurafilm'),
            (1407, 'Children''s Playground Entertainment'),
            (1414, 'bilibili'),
            (1419, 'GARDEN LODGE'),
            (1420, 'SIDO LIMITED'),
            (1421, 'Takara Tomy A.R.T.S'),
            (1424, 'Mediabank'),
            (1426, 'Studio Meditation With a Pencil'),
            (1433, 'Ekura Animal'),
            (1435, 'JCF'),
            (1436, 'Stingray'),
            (1437, 'Ishimori Entertainment'),
            (1440, 'Felix Film'),
            (1441, 'Mippei Eigeki Kiryuukan'),
            (1442, 'Mook DLE'),
            (1443, 'Overlap'),
            (1444, 'Egg Firm'),
            (1445, 'Arcs Create'),
            (1451, 'TYO'),
            (1454, 'REALTHING'),
            (1456, 'Beijing Huihuang Animation Company'),
            (1460, 'Coastline Animation Studio'),
            (1462, 'B&T'),
            (1463, 'Anime Antenna Iinkai'),
            (1464, 'Hiro Media'),
            (1465, 'Beijing Enlight Pictures'),
            (1471, 'Platinum Vision'),
            (1472, 'Myung Films'),
            (1473, 'Odolttogi'),
            (1476, 'Shochiku Animation Institute'),
            (1479, 'Studio Core'),
            (1482, 'Bouncy'),
            (1485, 'Light Chaser Animation Studios'),
            (1487, 'Bouncy'),
            (1489, 'Ripromo'),
            (1504, 'Studio Z5'),
            (1505, 'Studio March'),
            (1509, 'Studio World'),
            (1512, 'Dai-Ichi Douga'),
            (1513, 'Dongyang Animation'),
            (1514, 'Tengu Kobo'),
            (1517, 'Jinnan Studio'),
            (1521, 'Studio Elle'),
            (1522, 'Echoes'),
            (1523, 'Studio Ponoc'),
            (1524, 'Geidai Animation'),
            (1525, 'Moss Design Unit'),
            (1527, 'Image House'),
            (1529, 'Studio M2'),
            (1530, 'Emon'),
            (1531, 'Flavors Soft'),
            (1533, 'Studio WHO'),
            (1536, 'Namu Animation'),
            (1545, 'Japan Taps'),
            (1546, 'Chippai'),
            (1547, 'Blade'),
            (1549, 'Dai Nippon Printing'),
            (1558, 'TOCSIS'),
            (1560, 'Yaoyorozu'),
            (1562, 'Team YokkyuFuman'),
            (1567, 'Nut'),
            (1569, 'Seven Arcs Pictures'),
            (1572, 'XFLAG'),
            (1573, 'XFLAG Pictures'),
            (1575, 'DR Movie'),
            (1587, 'Cygames'),
            (1591, 'Science SARU'),
            (1592, 'Kamio Japan'),
            (1593, 'Success Corp.'),
            (1596, 'Will Palette'),
            (1618, 'Rockwell Eyes'),
            (1638, 'Tsukimidou'),
            (1639, 'Chiptune'),
            (1641, 'Studio AWAKE'),
            (1642, 'Circle Tribute'),
            (1650, 'Twilight Studio'),
            (1661, 'drop'),
            (1662, 'Creators Dot Com'),
            (1667, 'Foch Film'),
            (1668, 'Karasfilms'),
            (1669, 'production doA'),
            (1670, 'Nishiki Studio'),
            (1671, 'DMM pictures'),
            (1673, 'DMM.futureworks'),
            (1678, 'Yuhodo'),
            (1684, 'THINKR'),
            (1687, 'Yokohama Animation Lab'),
            (1690, 'Imagineer'),
            (1691, 'Studio UGOKI'),
            (1692, 'Revoroot'),
            (1693, 'Studio Flad'),
            (1694, 'AZ Creative'),
            (1696, 'Kadokawa'),
            (1705, 'Studio Khronos'),
            (1706, 'Beijing Rocen Digital'),
            (1717, 'Onionskin'),
            (1721, 'Gold Bear'),
            (1722, 'Bibury Animation Studios'),
            (1723, 'Anime Beans'),
            (1724, 'Studio OX'),
            (1725, 'Minakata Laboratory'),
            (1726, 'Three-d'),
            (1727, 'Tencent Penguin Pictures'),
            (1728, 'China Literature Limited'),
            (1746, 'Pops Inc.'),
            (1747, 'Twin Engine'),
            (1750, 'Studio CA'),
            (1751, 'pH Studio'),
            (1753, 'D & D Pictures'),
            (1754, 'Meruhensha'),
            (1758, 'Picante Circus'),
            (1759, 'Lyrics'),
            (1760, 'Suiseisha'),
            (1762, 'Piso Studio'),
            (1763, 'Studio Nanahoshi'),
            (1764, 'Picona'),
            (1766, 'Husio Studio'),
            (1767, 'iDRAGONS Creative Studio'),
            (1768, 'Sparkly Key Animation Studio'),
            (1769, 'helo.inc'),
            (1770, 'KIZAWA Studio'),
            (1771, 'Pb Animation'),
            (1772, 'Wawayu Animation'),
            (1773, 'KJJ Animation'),
            (1774, 'LAN Studio'),
            (1776, 'Studio Mir'),
            (1793, 'Happy Elements'),
            (1794, 'EKACHI EPILKA'),
            (1795, 'CUCURI'),
            (1796, 'Digital Network Animation'),
            (1797, 'NHK Enterprises'),
            (1800, 'Marui Group'),
            (1804, 'Nice Boat Animation'),
            (1805, 'Thundray'),
            (1807, '2:10 Animation'),
            (1808, 'CG Year'),
            (1809, 'October Media'),
            (1810, 'Mili Pictures'),
            (1811, 'Boyan Pictures'),
            (1812, 'Imagica Imageworks'),
            (1813, 'Studio Lings'),
            (1814, 'Studio Hakk'),
            (1827, 'Motion Magic'),
            (1828, 'Lapin Track'),
            (1829, 'Lesprit'),
            (1830, 'Seven Stone Entertainment'),
            (1831, 'Colored Pencil Animation Japan'),
            (1832, 'GRIZZLY'),
            (1835, 'CloverWorks'),
            (1836, 'SELFISH'),
            (1837, 'G-angle'),
            (1838, '33 Collective'),
            (1839, 'Studio Ppuri'),
            (1842, 'Urban Product'),
            (1843, 'TriF Studio'),
            (1844, 'Shanghai Hippo Animation'),
            (1845, 'Guton Animation Studio'),
            (1846, 'Tokyo Movie'),
            (1847, 'Square Enix Visual Works'),
            (1848, 'Dancing CG Studio'),
            (1849, 'MASTER LIGHTS'),
            (1851, 'Jumonji'),
            (1853, 'Saetta'),
            (1854, 'monofilmo'),
            (1857, 'Geek Toys'),
            (1860, 'Magia Doraglier'),
            (1861, 'Animation Planet'),
            (1864, 'Ezόla'),
            (1866, 'Grom'),
            (1867, 'Aurum Production'),
            (1871, 'Studio W.Baba'),
            (1872, 'P.I.C.S.'),
            (1873, 'Silver'),
            (1874, 'Arvo Animation'),
            (1876, 'CLAP'),
            (1879, 'Dangun Pictures'),
            (1881, 'Friendly Land'),
            (1882, 'UWAN Pictures'),
            (1887, 'Brio Animation'),
            (1890, 'Tear Studio'),
            (1892, 'Sublimation'),
            (1893, 'CygamesPictures'),
            (1897, 'Ankama Animations'),
            (1903, 'IMAGICA Lab.'),
            (1906, 'animate'),
            (1910, 'Sega Interactive'),
            (1927, 'Studio Crocodile'),
            (1930, 'Zelico Film'),
            (1932, 'Speed Inc.'),
            (1934, 'Saigo no Shudan'),
            (1936, 'Liberty Animation Studio'),
            (1937, 'MAT'),
            (1938, 'Polygon Magic'),
            (1939, 'Alpha Animation'),
            (1940, 'Da Huoniao Donghua'),
            (1943, 'Idol'),
            (1944, 'Samsara Animation Studio'),
            (1945, 'Lide'),
            (1947, 'Kate Arrow'),
            (1949, 'Anon Pictures'),
            (1951, 'ANIDO FILM'),
            (1952, 'Animation Staff Room'),
            (1953, 'W+K Tokyo'),
            (1954, 'Welz Animation Studios'),
            (1958, 'YHKT Entertainment'),
            (1959, 'Green Monster Team'),
            (1960, 'StoryRiders Co. Ltd.'),
            (1961, 'Creatures'),
            (1966, 'Arch'),
            (1967, 'Drive'),
            (1968, 'Studio Hokiboshi'),
            (1969, 'V-sign'),
            (1970, 'Wolf Smoke Studio'),
            (1971, 'Gainax Kyoto'),
            (1972, 'HOTZIPANG'),
            (1973, 'Monster''s Egg'),
            (1974, 'ENGI'),
            (1975, 'Qubic Pictures'),
            (1976, 'CGCG Studio'),
            (1978, 'Maho Film'),
            (1979, 'Suna Kouhou'),
            (1980, 'Big Firebird Culture'),
            (1982, 'LIDENFILMS Osaka Studio'),
            (1983, 'Anima&Co.'),
            (1984, 'Bakken Record'),
            (1991, 'Enishiya'),
            (1992, 'Bandai Spirits'),
            (1993, 'Studio Bind'),
            (1995, 'Live2D Creative Studio'),
            (1997, 'Studio KAI'),
            (1998, 'Studio Signpost'),
            (1999, 'Albacrow'),
            (2004, 'Sunrise Beyond'),
            (2007, 'Studio Drive'),
            (2009, 'Yostar Pictures'),
            (2010, 'Nippon Ramayana Film'),
            (2011, 'Yonago Gainax'),
            (2013, 'Peak Hunt'),
            (2014, 'Nur'),
            (2020, 'Ark'),
            (2022, 'TYMOTE'),
            (2023, 'Spoon'),
            (2027, 'Team TillDawn'),
            (2029, 'Earth Design Works'),
            (2032, 'WHOPPERS'),
            (2033, 'FILMONY'),
            (2034, 'Akatsuki'),
            (2037, 'Okuruto Noboru'),
            (2040, 'Maro Studio'),
            (2041, 'Enjin Productions'),
            (2042, 'Ruo Hong Culture'),
            (2046, 'Dazzling Star'),
            (2047, 'Pancake'),
            (2048, 'ASK Animation Studio'),
            (2049, 'BOMB! CUTE! BOMB!'),
            (2050, 'Trash Studio'),
            (2051, 'Studio Coa'),
            (2052, 'Wolfsbane'),
            (2053, 'l-a-unch・BOX'),
            (2054, 'MORIE Inc.'),
            (2055, 'BYMENT'),
            (2056, 'DRAWIZ'),
            (2057, 'Toho Interactive Animation'),
            (2058, 'Shengying Animation'),
            (2059, 'Suoyi Technology'),
            (2060, 'Wulifang'),
            (2061, 'Kaca Entertainment'),
            (2063, 'Spell Bound'),
            (2064, 'Mokai Technology'),
            (2065, 'Original Force'),
            (2066, 'Congzhuo Animation'),
            (2067, 'Flat Studio'),
            (2068, 'Ai Si Animation Studio'),
            (2069, 'Making Animation'),
            (2070, 'Wei Chuang Jiang Xin'),
            (2071, 'AQUA ARIS'),
            (2073, 'Painting Dream'),
            (2075, 'Taomee'),
            (2076, 'Fenz'),
            (2078, 'HIDEHOMARE'),
            (2079, 'Animation Lab Japan'),
            (2080, 'Super Normal Studio'),
            (2081, 'JJJOY Animation Studios'),
            (2082, 'Benlai Pictures'),
            (2084, 'Tong Mingxuan Studio'),
            (2085, 'Acca effe'),
            (2086, 'Giga Production'),
            (2087, 'CEKAI'),
            (2089, 'Wan Wei Mao Donghua'),
            (2091, 'Xanthus Media'),
            (2097, 'HORNETS'),
            (2114, 'Ether Kitten'),
            (2115, 'Gosay Studio'),
            (2122, 'PERIMETRON'),
            (2123, 'foodunited.'),
            (2125, 'LICO'),
            (2126, 'Red Dog Culture House'),
            (2129, 'Visual Flight'),
            (2130, 'Studio Shelter'),
            (2133, 'Djinn Power'),
            (2134, 'Studio CANDY BOX'),
            (2136, 'Ten Tails Animation'),
            (2137, '1IN'),
            (2140, 'Qianqi Animation'),
            (2141, 'TANOsim'),
            (2142, 'LEVELS'),
            (2143, 'LX Animation Studio'),
            (2144, 'BloomZ'),
            (2151, 'Ekakiya'),
            (2157, 'Production +h.'),
            (2158, 'Durufix'),
            (2159, 'Composition Inc.'),
            (2161, 'Suspenders'),
            (2162, 'Maxilla'),
            (2163, 'Teatro Nishi Tokyo Studio'),
            (2164, 'Super Brain'),
            (2167, 'Hololive Production'),
            (2168, 'Okuroto Noboru'),
            (2169, 'Studio 88'),
            (2170, 'Alpha Group'),
            (2171, 'Paper Animation'),
            (2172, 'Original Dream'),
            (2175, 'GARDEN Culture'),
            (2177, 'Mimoid'),
            (2178, 'Tecarat'),
            (2179, 'FIREBUG'),
            (2183, 'Keica'),
            (2184, 'The Monk Studios'),
            (2188, 'Marone'),
            (2191, 'BUILD DREAM'),
            (2192, 'Haianxian Donghua Gongzuoshi'),
            (2193, 'ORENDA'),
            (2194, 'Yi Chen Animation'),
            (2195, 'PONOS Corporation'),
            (2196, 'Studio DURIAN'),
            (2198, 'Irawias'),
            (2201, 'Studio Palette'),
            (2202, 'Front Wing'),
            (2204, 'OZ'),
            (2205, 'Studio Kafka'),
            (2206, 'Xuni Ying Ye'),
            (2207, 'Poly Animation'),
            (2208, 'Taikong Works'),
            (2209, 'Reiki Eyes Animation'),
            (2210, 'Jichitai Anime'),
            (2211, 'Lingsanwu Animation'),
            (2212, 'Tsumugi Akita Animation Lab'),
            (2213, 'Magma Studio'),
            (2214, 'Takun Manga Box'),
            (2216, 'CMAY Animation'),
            (2226, 'Gambit'),
            (2233, 'Starry Cube'),
            (2239, 'Transcendence Picture'),
            (2240, 'Studio Daisy'),
            (2241, 'Dawn Animation'),
            (2243, 'Quebico'),
            (2244, 'Studio Gohan'),
            (2246, 'studio MOTHER'),
            (2247, 'Delight Animation'),
            (2248, 'Indivision'),
            (2249, 'Flagship Line'),
            (2250, 'Spooky graphic'),
            (2251, 'TthunDer Animation'),
            (2252, 'Studio Kingyoiro'),
            (2253, 'miHoYoAnime'),
            (2256, 'Kitty Film Mitaka Studio'),
            (2257, 'XEBEC M2'),
            (2258, 'Sharefun Studio'),
            (2264, '5 Inc.'),
            (2265, 'ARECT'),
            (2266, 'Planet Nemo Animation'),
            (2267, 'MMT Technology'),
            (2268, 'Point Pictures'),
            (2269, 'New Generation'),
            (2270, 'Wise Guy'),
            (2274, 'Qiying Animation'),
            (2275, 'Drawing and Manual'),
            (2276, 'Project Team Sarah'),
            (2277, 'Network Kouenji Studio'),
            (2281, 'Rocen'),
            (2282, 'Studio Guts'),
            (2283, 'Manga Productions'),
            (2284, 'SJYNEXCUS'),
            (2288, 'Qzil.la'),
            (2292, 'Toei Advertising'),
            (2294, 'AHA Entertainment'),
            (2295, 'Story Effect'),
            (2296, 'Studio Nuck'),
            (2297, 'EXNOA'),
            (2298, 'Atelier Pontdarc'),
            (2299, 'Gift-o’-Animation'),
            (2300, 'Studio Jemi'),
            (2301, 'Borutong'),
            (2302, 'Nostalook'),
            (2303, 'Noovo'),
            (2304, 'TrioPen Studio'),
            (2305, 'Fukushima Gaina'),
            (2306, 'LIDENFILMS Kyoto Studio'),
            (2309, 'Kamitsubaki Studio'),
            (2310, 'Paper Plane Animation Studio'),
            (2311, 'Gyorai Eizo Inc.'),
            (2313, 'studio hb'),
            (2314, 'Quad'),
            (2315, 'Office No. 8'),
            (2316, 'Maboroshi Koubou'),
            (2317, 'Dream Entertainment'),
            (2318, 'ORADA COMPANY'),
            (2319, 'Datama Film'),
            (2320, 'Inugoya'),
            (2321, 'Production D.M.H'),
            (2322, 'Mousou Senka'),
            (2323, 'Cafe de Jeilhouse'),
            (2325, 'Bibury Animation CG'),
            (2326, 'OLM Team Yoshioka'),
            (2327, 'Studio Boogie Nights'),
            (2328, 'Sonsan Kikaku'),
            (2329, 'Shinjukuza'),
            (2330, 'Meltdown'),
            (2331, 'Shura'),
            (2332, 'Shion'),
            (2333, 'Space-X'),
            (2334, 'Mouse'),
            (2335, 'Shindeban Film'),
            (2336, 'Lead'),
            (2337, 'Studio Soul'),
            (2338, 'Studio Ten'),
            (2339, 'Melissa'),
            (2340, 'Cutie Bee'),
            (2341, 'Studio Prokion'),
            (2342, 'PP Project'),
            (2344, 'All Products'),
            (2345, 'Onion Studio'),
            (2346, 'Alice Production'),
            (2347, 'IKK Room'),
            (2348, 'KKC Animation Production'),
            (2349, 'Potato House'),
            (2350, 'Kantou Douga Kai'),
            (2351, 'Studio Gadget'),
            (2352, 'Tryforce'),
            (2353, 'P core'),
            (2355, 'Alfred Imageworks'),
            (2356, 'Kung Fu Frog Animation'),
            (2358, 'Big Wing'),
            (2359, 'Aiko'),
            (2360, 'Amarcord'),
            (2361, 'Okumaza'),
            (2362, 'Aiti St.'),
            (2363, 'JOF'),
            (2364, 'Hanjin Animation'),
            (2365, 'MI'),
            (2366, 'Kigumi'),
            (2368, 'Miyuki Production'),
            (2370, 'Hayabusa Film'),
            (2371, 'Planet Cartoon'),
            (2372, 'Flint Sugar'),
            (2374, 'Momoi Planning'),
            (2375, 'GAV Video'),
            (2378, 'StarLink'),
            (2379, 'Scooter Films'),
            (2382, 'J.T.P.P.'),
            (2387, 'Ga-Crew'),
            (2388, 'Ai Yume Mai'),
            (2389, 'G.P Entertainment'),
            (2390, 'Concept Films'),
            (2391, 'Sumomo Film'),
            (2392, 'Ishibashi Planning'),
            (2393, 'MB planning'),
            (2394, 'MoMo Production'),
            (2395, 'J.C.F.'),
            (2396, 'Joicy Studio'),
            (2397, 'Pink Cat'),
            (2398, 'VCRWORKS'),
            (2399, 'Eshoya Honpo'),
            (2400, 'Executive Decision'),
            (2401, 'YURUPPE Inc.'),
            (2403, 'Brians Film'),
            (2404, 'OLM Team Kato'),
            (2405, 'Staple Entertainment'),
            (2406, 'Eallin'),
            (2407, 'Flying Ship Studio'),
            (2409, 'Amineworks'),
            (2410, 'Gonzino'),
            (2411, 'Studio Massket'),
            (2412, 'FUNNY MOVIE'),
            (2413, 'AION Studio'),
            (2414, 'MontBlanc Pictures'),
            (2415, 'HuaMei Animation'),
            (2416, 'Kent House'),
            (2417, 'TiMi Studio Group'),
            (2418, 'Imagica Digitalscape'),
            (2419, 'd00r works'),
            (2420, 'Tang Kirin Culture'),
            (2421, 'M&M'),
            (2424, 'Bandai Namco Filmworks'),
            (2429, 'STUDIO6''oN'),
            (2432, 'happyproject'),
            (2436, 'Frontier One'),
            (2437, 'Infinity Vision'),
            (2438, 'yell'),
            (2439, 'Chosen'),
            (2444, 'Hanho Heung-Up'),
            (2445, 'Big Film Entertainment'),
            (2447, 'Youku'),
            (2449, 'Atorie A.B.C.'),
            (2450, 'C and R'),
            (2451, 'TEC'),
            (2452, 'Project Team Muu'),
            (2453, 'Kusama Art'),
            (2454, 'Ryuu M''s'),
            (2455, 'East Fish Studio'),
            (2456, 'team Yamahitsuji'),
            (2457, 'Studio Ranmaru'),
            (2459, 'Studio Gazelle'),
            (2460, 'aNCHOR'),
            (2461, 'Twenty First'),
            (2462, 'Seasun Pictures'),
            (2463, 'Cloud Art'),
            (2469, 'HM Heros'),
            (2471, 'Wonder Cat Animation'),
            (2472, 'High Energy Studio'),
            (2474, 'Haneda xR Studio'),
            (2478, 'Oriental Creative Color'),
            (2481, 'Chimu Jika Hatsuden'),
            (2482, 'Atti Production'),
            (2484, 'Gunners'),
            (2485, 'Ezo Kobo'),
            (2486, 'Blue Note'),
            (2487, 'Kyushu Network Animation'),
            (2488, 'J.K.I'),
            (2489, 'Tsubo Production'),
            (2490, 'Studio Dolphin Night'),
            (2491, 'Mikimoto Production'),
            (2492, 'Studio Jin'),
            (2493, 'Studio B&M'),
            (2494, 'Enzo Animation'),
            (2503, '7doc'),
            (2508, 'Deck'),
            (2509, 'Colored Pencil Animation'),
            (2512, 'Studio Easter'),
            (2513, 'HMCH'),
            (2514, 'AIC Project'),
            (2520, 'Twilight Town'),
            (2521, 'Qiyuan Yinghua'),
            (2525, 'Hurray!'),
            (2526, 'Shenman Entertainment'),
            (2527, 'Liber'),
            (2528, 'Passion Paint Animation'),
            (2529, 'Xing Yi Kai Chen'),
            (2530, 'Blue bread'),
            (2534, 'studio YOG'),
            (2535, 'Uguisu Kobo'),
            (2538, 'Imagestone Inc.'),
            (2540, 'Fever Creations'),
            (2541, 'SAMG Entertainment'),
            (2544, 'Kami Kukan'),
            (2546, 'Studio Sota'),
            (2547, 'Frontier Engine'),
            (2549, 'StudioXD'),
            (2550, 'ONIRO'),
            (2551, 'Animation 501'),
            (2552, 'C&S Production'),
            (2553, 'Garyuu Studio'),
            (2554, 'Gekkou'),
            (2555, 'Year Young Culture'),
            (2558, 'Delpic'),
            (2559, 'Guo Pengzi Studio'),
            (2560, 'Nekonigashi Inc.'),
            (2561, 'OTOIRO'),
            (2562, 'Studio Himalaya'),
            (2563, 'Studio Tumble'),
            (2564, 'Yamiken'),
            (2569, 'Yinhe Changxing Culture'),
            (2570, 'Ijigen Tokyo'),
            (2571, 'Griot Groove'),
            (2572, 'Adonero'),
            (2573, 'Watanabe Promotion'),
            (2574, 'Circus Production'),
            (2576, 'General Entertainment'),
            (2580, 'GUMBLAB'),
            (2586, 'D.ROCK-ART'),
            (2591, 'Studio Pivote'),
            (2593, 'Angle'),
            (2595, 'TypeZero'),
            (2596, 'Comma Studio'),
            (2597, 'Wong Ping Animation Lab'),
            (2598, 'Bigcat Studio'),
            (2600, 'Cloud Hearts'),
            (2601, 'Sunflowers'),
            (2604, 'DC Impression Vision'),
            (2605, 'Tonari Animation'),
            (2606, 'Toyo Links Corporation'),
            (2611, 'Fantawild Animation'),
            (2612, 'Fengyun Animation'),
            (2613, 'Aurora Animation'),
            (2614, 'Chongzhuo Animation'),
            (2617, 'Tianshi Wenhua'),
            (2619, 'Quyue Technology'),
            (2620, 'Manhoo Culture'),
            (2622, 'Makaria'),
            (2623, 'Dyna Method'),
            (2624, 'Village Studio'),
            (2625, 'Square Pictures'),
            (2626, 'Studio D-Volt'),
            (2628, 'Xiaoming Taiji'),
            (2635, 'Escape Velocity Animation'),
            (2636, 'Qingxiang Culture'),
            (2638, 'Yien Animation Studio'),
            (2641, 'Locus Corporation'),
            (2642, 'E&H Production'),
            (2644, 'Kuai Ying Hu Yu'),
            (2645, 'Liyu Culture'),
            (2646, 'trenova'),
            (2647, 'Studio A. Craft'),
            (2648, 'Au Praxinoscope'),
            (2649, 'LB Commerce'),
            (2651, 'Stereotype'),
            (2652, 'Gravity Well'),
            (2656, 'UchuPeople'),
            (2657, 'NANON CREATIVE'),
            (2658, 'flag Co.'),
            (2660, 'UKA'),
            (2661, 'Kinematics'),
            (2663, 'Rock''n Roll Mountain'),
            (2665, 'AMGA'),
            (2666, 'EOEO System'),
            (2667, 'Keyring'),
            (2669, 'THINGS.'),
            (2673, 'Goto Inc.'),
            (2674, 'BUG FILMS'),
            (2676, 'Pmats9 studio'),
            (2677, 'Central Animation Studio'),
            (2678, 'Slow Studio'),
            (2679, 'cogitoworks'),
            (2682, 'Steamworks'),
            (2684, 'CHOCOLATE'),
            (2686, 'EDP graphic works'),
            (2688, 'Saber Project'),
            (2692, 'Ice Butter'),
            (2693, '6pucks'),
            (2694, 'studio NAGURI'),
            (2695, 'SIGNIF'),
            (2696, '100studio'),
            (2698, 'Voil'),
            (2701, 'CMC Media'),
            (2702, 'HuaDream'),
            (2703, 'Oyster'),
            (2705, 'TOHO animation STUDIO'),
            (2706, 'Hananona Studio'),
            (2711, 'Miyu Productions'),
            (2712, 'Studio G7'),
            (2713, 'Infinity Animations'),
            (2714, 'evg'),
            (2715, 'Hand to Mouse.'),
            (2721, 'NHK Art'),
            (2722, 'Studio Fusion'),
            (2723, 'Unend'),
            (2724, 'Heart & Soul Animation'),
            (2725, 'CompTown'),
            (2726, 'Laftel'),
            (2728, 'New Deer'),
            (2729, 'CANON RECORDINGS'),
            (2736, 'Gone-zo'),
            (2737, 'Painted Blade Studio'),
            (2742, 'Studio N'),
            (2743, 'Shengguang Knight Culture'),
            (2744, 'Hong Ying Animation'),
            (2746, 'Studio Vandal'),
            (2748, 'Sankaku'),
            (2749, 'Anime Tokyo'),
            (2750, 'Hu Po Donghua'),
            (2752, 'Youliao Studio'),
            (2753, 'Whatever'),
            (2754, 'Contrail'),
            (2755, 'Congrong Film'),
            (2756, 'Equator'),
            (2757, 'Caviar'),
            (2760, 'Studio Add'),
            (2761, 'ARCUS'),
            (2762, 'Studio Matomo'),
            (2764, 'Studio HUIT'),
            (2765, 'Bebow'),
            (2767, 'Euluca Lab'),
            (2772, 'Misogo Animation Studio'),
            (2773, 'Transistor Studio'),
            (2774, 'Shadow Steps'),
            (2775, 'Production Wave'),
            (2778, 'Sasayuri'),
            (2779, 'Studio BAZOOKA'),
            (2780, 'Studio Artegg'),
            (2781, 'Cloud Culture'),
            (2783, 'ANYZAC'),
            (2784, 'Medo'),
            (2785, 'Shikachan Studio'),
            (2787, 'Studio Lemon'),
            (2790, 'Hezmon Animation'),
            (2792, 'INTERFACEDOGS'),
            (2794, 'BUDDHA INC.'),
            (2795, 'Xing Xing Donghua'),
            (2802, 'Yudubai Animation'),
            (2804, 'Seoul Movie'),
            (2807, 'ABJ COMPANY'),
            (2809, 'PHANTOM'),
            (2810, 'Studio Yona'),
            (2812, 'Zuiyo'),
            (2813, 'Iconix Entertainment'),
            (2814, 'Image Studio 109'),
            (2818, 'qmotri'),
            (2819, 'soket'),
            (2820, 'maroyaka'),
            (2821, 'Fugaku'),
            (2822, 'Shykeumo Animation Studio'),
            (2824, 'Production HASU'),
            (2828, 'Studio Polon'),
            (2829, 'EOTA'),
            (2830, 'Artner'),
            (2831, 'uzupiyo Animation & Digital Works'),
            (2832, 'VROOOOM'),
            (2833, 'Sofix'),
            (2834, 'Hero'),
            (2835, 'ROLL2'),
            (2838, 'San Blas Animation'),
            (2841, 'Maruga Factory'),
            (2842, 'Big Pine Animation Studio'),
            (2844, 'Imagica Infos'),
            (2845, 'Dimps'),
            (2846, 'Studio Bingo'),
            (2848, 'Taiko Studios'),
            (2850, 'SAFEHOUSE'),
            (2851, 'Pinkfong'),
            (2853, 'ASTROBROS.'),
            (2854, 'Volca'),
            (2855, 'Studio Moe'),
            (2857, 'CELAVIE'),
            (2858, 'Makino Production'),
            (2859, '924 Studio'),
            (2860, 'CANOPUS'),
            (2861, 'KWANED'),
            (2863, 'Miota'),
            (2864, 'Windy Studio'),
            (2870, 'Alke'),
            (2875, 'Blaze Studio'),
            (2877, 'D''ART Shtajio'),
            (2878, 'Khaki'),
            (2879, 'Grayscale Arts'),
            (2880, 'ORCEN'),
            (2881, 'Andraft'),
            (2882, 'THREE IS A MAGIC NUMBER'),
            (2883, 'Atelier Tuki'),
            (2885, 'Group Creato'),
            (2888, 'Wang Film Productions'),
            (2891, 'A4A Inc.'),
            (2892, 'WWWave'),
            (2893, 'Gear Studio'),
            (2894, 'Konami animation'),
            (2895, 'Team OneOne'),
            (2897, 'MOJO Animation'),
            (2898, 'Manaa Animation'),
            (2906, 'Kobito'),
            (2907, 'Studio Placebo'),
            (2909, 'Teddy'),
            (2911, 'Studio Eight Color'),
            (2914, 'Creative House Pocket'),
            (2916, 'Reirs'),
            (2917, 'Soigne'),
            (2919, 'Le-joy Animation Studio'),
            (2921, 'Public Enemies'),
            (2928, 'Elias'),
            (2929, 'Studio Outrigger'),
            (2931, 'Buyuu'),
            (2933, 'Hutoon Animation'),
            (2934, 'studio2 Animation Lab'),
            (2936, 'G&G Direction'),
            (2938, '3D'),
            (2939, 'Studio Gale'),
            (2940, 'Ocon Studio'),
            (2944, 'Brick Studio'),
            (2945, 'Studio Goindol'),
            (2947, 'Tokyo TV Douga'),
            (2948, 'Nippon TV Douga'),
            (2949, 'Oriental Creative Color'),
            (2950, 'studio ALBLE'),
            (2951, 'Pierrot Films'),
            (2953, 'Flying Monkeys Production'),
            (2954, 'Studio Button'),
            (2955, 'Sunny Gapen'),
            (2957, 'Particlefield'),
            (2967, 'Digital Dream Studios'),
            (2969, 'Mainichi Eigasha'),
            (2970, '717 Animation Studio'),
            (2972, 'Cocktail Media'),
            (2977, 'BlueArc Animation Studios'),
            (2982, 'Ginga Teikoku'),
            (2983, 'Imageworks Studio'),
            (2985, 'Saber Works'),
            (2986, 'Sugata Creative & Design'),
            (2987, 'Outline'),
            (2988, 'Shadow Pond Studio'),
            (2989, 'LIGHTAIR Inc.'),
            (2990, 'Higashinaka Studio'),
            (2991, 'Skydance Animation'),
            (2992, 'R11R'),
            (2994, 'Aurochs'),
            (2997, 'Million Volt'),
            (3002, 'CUEBiC'),
            (3007, 'Studio Harutonari'),
            (3009, 'Kitchen Ltd.'),
            (3013, 'Rhythmos'),
            (3014, 'STUDIOK110'),
            (3022, 'Panda Tower Studio'),
            (3023, 'FAB'),
            (3030, 'Studio Dotou'),
            (3031, 'Kassen'),
            (3032, 'OutSide Directors Company'),
            (3033, 'Studio Barcelona'),
            (3035, 'Koinrush Studio'),
            (3036, 'MARK'),
            (3040, 'Durandal'),
            (3042, 'Project Studio Q'),
            (3044, 'Bellnox Films'),
            (3045, 'Bones Film'),
            (3046, 'Tsumupapa'),
            (3048, 'Kachigarasu'),
            (3049, 'STUDIO 8 DOGS'),
            (3050, 'Crew-Cell'),
            (3052, 'Studio KeepFire'),
            (3055, 'Animation Studio Wagumi'),
            (3060, 'WonderLand'),
            (3061, 'AOI Pro.'),
            (3062, 'DEFT'),
            (3066, 'Aeonium'),
            (3068, 'Manpuku Jinja'),
            (3070, 'Studio Clutch'),
            (3071, 'Shuiniu Dongman'),
            (3073, 'Yasuda Genshou Studio by Xenotoon'),
            (3074, 'Kumarba'),
            (3076, 'No Side'),
            (3077, 'Axis'),
            (3078, 'Studio LEO'),
            (3079, 'LinQ'),
            (3081, 'Fortes'),
            (3082, 'teevee graphics'),
            (3083, 'Nagomi'),
            (3085, 'I&A'),
            (3086, 'ILCASHIPS'),
            (3089, 'StealthWorks'),
            (3090, 'MAINCONCEPT'),
            (3091, 'KaKa Technology Studio'),
            (3093, 'Sanjie Donghua'),
            (3094, 'animation studio42'),
            (3097, 'Maru Animation'),
            (3099, 'sugarsaltpepper'),
            (3107, 'Hifumi'),
            (3111, 'Raiose'),
            (3116, 'ame pippin'),
            (3117, 'Jiman Wenhua'),
            (3120, 'Stellar Pictures'),
            (3121, 'Happy Toon'),
            (3122, 'Climax Studio'),
            (3124, 'Yumao Wenhua'),
            (3125, 'G.H.Y. Culture & Media'),
            (3126, 'Long Zhi Gu Wenhua'),
            (3127, 'INS Studio'),
            (3128, 'Guangzhou Liu Ling Yi'),
            (3129, 'Hei Chao Yinghua'),
            (3130, 'Chenghuang Yinghua'),
            (3131, 'Zhou Ling Wenhua'),
            (3132, 'Flying Fish Studio'),
            (3133, 'Bu Keneng de Shijie'),
            (3134, 'Kid+Kid Animation Studio'),
            (3135, 'Lan Ying Yingshi'),
            (3136, 'Tang Cai Zhaopin'),
            (3138, 'Honoo'),
            (3139, 'S.o.K'),
            (3142, 'Kagome Company'),
            (3143, 'ETERNA Animation'),
            (3144, 'Skyloong'),
            (3145, 'Nulls Design'),
            (3148, 'OSROCTION'),
            (3149, 'Pepper Conpanna'),
            (3150, 'Ziine Studio'),
            (3157, 'Psyde Kick Studio'),
            (3158, 'Children''s Corner'),
            (3159, 'Newon'),
            (3161, 'Triple A'),
            (3163, 'Woodpecker'),
            (3167, 'Funny Flux'),
            (3173, 'BENTEN Film'),
            (3179, 'TV Douga'),
            (3180, 'Number 19 Animation'),
            (3186, 'studio maf'),
            (3187, 'Cue'),
            (3189, 'mico.animation'),
            (3190, 'Studio Maybe'),
            (3192, 'Studio Graph77'),
            (3194, 'Nichicaline'),
            (3195, 'Folium'),
            (3196, 'Rouseact'),
            (3197, 'Toon Harbor Works'),
            (3201, 'ABC Animation Studio'),
            (3202, 'Finger and Toe'),
            (3205, 'Garage Film'),
            (3207, 'studioDOT'),
            (3209, 'IKIF+'),
            (3212, 'Tochka'),
            (3213, 'Shanghai Zhijian Network'),
            (3214, 'Studio BETTA'),
            (3217, 'Atoonz'),
            (3219, 'Nyan Pollution'),
            (3221, 'Miyajima Film'),
            (3223, 'Office Academy'),
            (3226, 'Studio Chromato'),
            (3228, 'Shou Fan Yu Shu Gongzuoshi'),
            (3230, 'Juvenage'),
            (3231, 'Qingkong Qian Li'),
            (3232, 'Left Pocket Studio'),
            (3233, 'Kio Studio'),
            (3234, 'InfiniOrange Animation Studio'),
            (3235, 'Origin'),
            (3236, 'Ke Yue Xue Zi'),
            (3237, 'Nothing New'),
            (3238, 'Tsubasa Production'),
            (3240, 'Soul Creative'),
            (3241, 'Project Team Argos'),
            (3243, 'Da Chenger Gongzuoshi'),
            (3244, 'Shenli Guangyin'),
            (3245, 'Teleimage'),
            (3247, 'bushes'),
            (3248, 'Igloo Studio'),
            (3249, 'Sunshine Corporation'),
            (3250, 'Lychee Time Media'),
            (3251, 'B.COOL STUDIO'),
            (3252, 'Doraku'),
            (3253, 'Liliyabi Company Introduction'),
            (3254, 'Honglu Technology'),
            (3255, 'PAINTFREE'),
            (3257, 'Grass Jelly Studio'),
            (3258, 'OCSTUDIO'),
            (3259, 'Moonseong Animation'),
            (3260, 'Hui Guang Gongzuoshi'),
            (3261, 'TRCARTOON'),
            (3264, 'BIGBIGSUN'),
            (3266, 'WINSING ANIMATION'),
            (3268, 'YNUO'),
            (3271, 'Gugenka'),
            (3273, 'Atelier Peuplier'),
            (3275, 'FuRyu Pictures'),
            (3276, 'Aura Studio'),
            (3277, 'Mofac Studio'),
            (3278, 'Studio Eek'),
            (3281, 'Akatsuki Media Studio'),
            (3282, 'Shen Fu Wenhua'),
            (3286, 'Cypic'),
            (3287, 'Daicon Film'),
            (3288, 'A4works'),
            (3290, 'Atra'),
            (3293, 'Green Leaf Animation'),
            (3294, 'Grass'),
            (3295, 'Computer Technique Group'),
            (3296, 'coyote'),
            (3297, 'Aisle'),
            (3300, 'Bakkka'),
            (3301, 'Cannon Code'),
            (3303, 'Daily Plan.net'),
            (3304, 'SO-DO Creative'),
            (3305, 'Electric Circus'),
            (3306, 'Studio Keel'),
            (3311, 'Kaihuang Donghua'),
            (3312, 'You Hu Wenhua'),
            (3314, 'Studio Wrong'),
            (3316, 'Ciwen Animation'),
            (3318, 'Buzhi Dongman'),
            (3319, 'Yanchester'),
            (3320, 'ZG-R'),
            (3321, 'HOTALL')
            ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name
        `);

        await queryRunner.query(`
            CREATE TABLE IF NOT EXISTS "anime_studios" (
                "anime_id" integer NOT NULL,
                "studio_id" integer NOT NULL,
                PRIMARY KEY ("anime_id", "studio_id")
            )
        `);

        await queryRunner.query(`
            INSERT INTO "anime_studios" ("anime_id", "studio_id")
            SELECT a.id, s.id
            FROM animes a
            CROSS JOIN LATERAL unnest(a.studios) AS studio_name
            JOIN studios s ON s.name = studio_name
            ON CONFLICT DO NOTHING
        `);

        await queryRunner.query(`ALTER TABLE "animes" DROP COLUMN IF EXISTS "studios"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "animes" ADD COLUMN IF NOT EXISTS "studios" text[]`);
        
        await queryRunner.query(`
            UPDATE "animes" a
            SET "studios" = (
                SELECT ARRAY_AGG(s.name)
                FROM "anime_studios" am
                JOIN "studios" s ON s.id = am.studio_id
                WHERE am.anime_id = a.id
            )
        `);
        
        await queryRunner.query(`DROP TABLE IF EXISTS "anime_studios" CASCADE`);
        await queryRunner.query(`DROP TABLE IF EXISTS "studios" CASCADE`);
    }
}
