import { MigrationInterface, QueryRunner } from "typeorm";

export class AddRussianNameForStudios1781665022304 implements MigrationInterface {
    name = 'AddRussianNameForStudios1781665022304'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "studios" ADD COLUMN IF NOT EXISTS "russian" character varying(256)`);

        const translations: Record<string, string> = {
            "TYMOTE": "ТИМОТЕ",
            "Spoon": "Спун",
            "Tonko House": "Тонко Хаус",
            "Bandai Spirits": "Бандай Спиритс",
            "Studio Drive": "Студия Драйв",
            "Unend": "Анэнд",
            "Shanghai Zhijian Network": "Шанхай Чжицзянь Нетворк",
            "Yonago Gainax": "Йонаго Гайнакс",
            "Studio Daisy": "Студия Дэйзи",
            "Akatsuki": "Акацуки",
            "Enjin Productions": "Энджин Продакшнс",
            "Team TillDawn": "Тим ТилДон",
            "Earth Design Works": "Эрф Дизайн Воркс",
            "Ark": "Арк",
            "Maro Studio": "Маро Студия",
            "Kyoto Animation": "Киото Анимейшн",
            "Character and Anime Dot Com": "Чарактер энд Аниме Дот Ком",
            "Aniplex": "Аниплекс",
            "Production I.G": "Продакшн АйДжи",
            "d-rights": "ди-райтс",
            "Marubeni": "Марубени",
            "Bee Media": "Би Медиа",
            "Bandai Visual": "Бандай Визуал",
            "Shinkai Makoto": "Синкай Макото",
            "VAP": "ВАП",
            "VCRWORKS": "ВСРВОРКС",
            "Myung Films": "Мьон Филмс",
            "Seven Arcs": "Севен Аркс",
            "m.o.e.": "м.о.э.",
            "GDH": "ДжиДиЭйч",
            "Daume": "Дауме",
            "Remic": "Ремик",
            "Composition Inc.": "Композишн Инк.",
            "Studio 88": "Студия 88",
            "Mimoid": "Мимойд",
            "Keica": "Кейка",
            "Brians Film": "Брайанс Филм",
            "OLM Team Kato": "ОЛМ Тим Като",
            "KSS": "КСС",
            "Pixy": "Пикси",
            "LMD": "ЛМД",
            "Avex Entertainment": "Авекс Энтертейнмент",
            "Staple Entertainment": "Стэйпл Энтертейнмент",
            "TV Asahi": "ТВ Асахи",
            "SILVER LINK.": "СИЛВЕР ЛИНК.",
            "Square Enix": "Сквер Эникс",
            "Beat Frog": "Бит Фрог",
            "Frontier Works": "Фронтир Воркс",
            "Trinet Entertainment": "Трайнет Энтертейнмент",
            "happyproject": "хэппипроджект",
            "Key": "Кей",
            "Four Some": "Фор Сам",
            "Front Line": "Фронт Лайн",
            "Khara": "Кхара",
            "Image Studio 109": "Имидж Студия 109",
            "PHANTOM": "ФАНТОМ",
            "qmotri": "Кмотри",
            "Khaki": "Хаки",
            "Andraft": "Андрафт",
            "THREE IS A MAGIC NUMBER": "ТРИ ИЗ Э МЭДЖИК НАМБЕР",
            "Polygon Magic": "Полигон Мэджик",
            "Mellow Head": "Меллоу Хэд",
            "Tokyo Movie Shinsha": "Токио Муви Синся",
            "Frontier One": "Фронтир Уан",
            "Nomad": "Номад",
            "Tecarat": "Текарат",
            "Trans Arts": "Транс Артс",
            "Yomiko Advertising": "Ёмико Адвертайзинг",
            "Silky' s": "Силкис",
            "CherryLips": "ЧерриЛипс",
            "G&G Entertainment": "ДжиДжи Энтертейнмент",
            "Zyc": "Зайк",
            "Marvelous Entertainment": "Марвелоус Энтертейнмент",
            "AIC Spirits": "АИС Спиритс",
            "Konami": "Конами",
            "BeSTACK": "БиСТЭК",
            "Starchild Records": "Старчайлд Рекордс",
            "Studio Flag": "Студия Флаг",
            "J.C.F.": "Дж.С.Ф.",
            "feel.": "Фил.",
            "BUILD DREAM": "Билд Дрим",
            "TV Osaka": "ТВ Осака",
            "ADV Films": "АДВ Филмс",
            "Sav! The World Productions": "Сэйв! Зе Ворлд Продакшнс",
            "Lantis": "Лантис",
            "Plum": "Плам",
            "Media Factory": "Медиа Фэктори",
            "Maru Production ": "Мару Продакшн",
            "AIC ASTA": "АИС АСТА",
            "ETERNA Animation": "ЭТЕРНА Анимейшн",
            "FUNimation Entertainment": "ФАНимейшн Энтертейнмент",
            "ORENDA": "ОРЕНДА",
            "Pink Cat": "Пинк Кэт",
            "Kitty Media": "Китти Медиа",
            "NHK Art": "ЭнЭйчКей Арт",
            "Shochiku": "Сётику",
            "Studio Matrix": "Студия Матрикс",
            "Broccoli": "Брокколи",
            "Studio Izena": "Студия Изена",
            "Diomedéa": "Диомедеа",
            "Active": "Эктив",
            "Tokyo Kids": "Токио Кидс",
            "Victor Entertainment": "Виктор Энтертейнмент",
            "Animac": "Анимак",
            "Pioneer Entertainment (USA)": "Пионер Энтертейнмент (США)",
            "Rondo Robe": "Рондо Роуб",
            "Shinyusha": "Синюся",
            "Yumeta Company": "Юмета Компани",
            "MediaNet": "МедиаНет",
            "Vega Entertainment": "Вега Энтертейнмент",
            "PPM": "ППМ",
            "Himajin Planning": "Химаджин Планинг",
            "Toei Video": "Тоэй Видео",
            "Asatsu DK": "Асацу ДК",
            "Mainichi Broadcasting": "Майничи Бродкастинг",
            "TBS": "ТБС",
            "CBC": "СиБиСи",
            "Flying Ship Studio": "Флайинг Шип Студия",
            "Studio Fusion": "Студия Фьюжн",
            "Animax": "Анимакс",
            "SKY Perfect Well Think": "СКАЙ Перфект Велл Тинк",
            "Hakunensha": "Хакунэнся",
            "SME Visual Works": "СМЕ Визуал Воркс",
            "Green Bunny": "Грин Банни",
            "SoftX": "СофтИкс",
            "Polygram Japan": "Полиграм Джапан",
            "BMG Japan": "БМГ Джапан",
            "KIDS STATION": "Кидс Стейшн",
            "Kodansha": "Коданся",
            "Sogo Vision": "Сого Вижн",
            "Sega": "Сега",
            "Shelty": "Шелти",
            "animate Film": "Анимейт Филм",
            "Amineworks": "Аминворкс",
            "Fuji TV": "Фудзи ТВ",
            "Imagica": "Имаджика",
            "Alchemist": "Алкемист",
            "A-Line": "АЛайн",
            "Yi Chen Animation": "И Чен Анимейшн",
            "PONOS Corporation": "ПОНОС Корпорейшн",
            "Studio DURIAN": "Студия ДУРИАН",
            "Movic": "Мовик",
            "Infinity Vision": "Инфинити Вижн",
            "Chosen": "Чозен",
            "East Fish Studio": "Ист Фиш Студия",
            "Liber": "Либер",
            "Alice Soft": "Алис Софт",
            "Sanrio": "Санрио",
            "Irawias": "Иравиас",
            "Ginga Ya": "Гинга Я",
            "Studio Kyuuma": "Студия Кюма",
            "Trilogy Future Studio": "Трилоджи Фьючер Студия",
            "Age": "Эйдж",
            "Agent 21": "Эйджент 21",
            "Ai ga areba Daijobu": "Ай га ареба Дайдзобу",
            "Aiko": "Айко",
            "Ail": "Аил",
            "GEN Productions": "ГЕН Продакшнс",
            "RCC Chugoku Broadcasting": "РСС Чугоку Бродкастинг",
            "Shinkuukan": "Синкукан",
            "Idea Factory": "Идеа Фэктори",
            "ANIK": "АНИК",
            "Studio Junior": "Студия Джуниор",
            "Gakken": "Гаккен",
            "Visual Art's": "Визуал Артс",
            "PIONEER LDC": "ПИОНЕР ЛДС",
            "Nihon Ad Systems": "Нихон Ад Системс",
            "Digital Works": "Диджитал Воркс",
            "Three Fat Samurai": "Три Фэт Самурай",
            "Sol Blade": "Сол Блейд",
            "Studio Tulip": "Студия Тьюлип",
            "Rakuonsha": "Ракуонся",
            "Venus Vangard": "Венус Вангард",
            "Half H.P Studio": "Халф ЭйчПи Студия",
            "BS-i": "БС-ай",
            "Nyan Pollution": "Нян Поллушн",
            "The Right Stuf International": "Зе Райт Стаф Интернэшнл",
            "Eiken": "Эйкен",
            "FUNNY MOVIE": "ФАННИ МУВИ",
            "Jade Animation": "Джейд Анимейшн",
            "Toshiba EMI": "Тосиба ИЭмАй",
            "Panmedia": "Панмедиа",
            "The Answer Studio": "Зе Ансвер Студия",
            "Barnum Studio": "Барнум Студия",
            "Studio Kajino": "Студия Кадзино",
            "Think Corporation": "Тинк Корпорейшн",
            "Misseri Studio": "Миссери Студия",
            "DLE": "ДЛЕ",
            "Studio Dolphin Night": "Студия Долфин Найт",
            "Heart & Soul Animation": "Харт Соул Анимейшн",
            "Bandai": "Бандай",
            "CyberConnect2": "СайберКоннект2",
            "Bandai Entertainment": "Бандай Энтертейнмент",
            "Studio Junio": "Студия Джунио",
            "YTV": "УайТиВи",
            "AT-X": "ЭйТи-Икс",
            "GUMBLAB": "ГАМБЛАБ",
            "Capcom": "Капком",
            "KOEI": "КОЭЙ",
            "D3": "Ди3",
            "Visual 80": "Визуал 80",
            "Studio Palette": "Студия Палетт",
            "Media Blasters": "Медиа Бластерс",
            "4Kids Entertainment": "4Кидс Энтертейнмент",
            "Tin House": "Тин Хаус",
            "Rikuentai": "Рикуэнтай",
            "Soft Garage": "Софт Гараж",
            "Studio Chromato": "Студия Хромато",
            "Studio Kikan": "Студия Кикан",
            "Jam": "Джем",
            "OZ": "ОЗ",
            "Kaeruotoko Shokai": "Каэруотоко Сёкай",
            "Shuuhei Morita": "Сюхэй Морита",
            "San-X": "Сан-Икс",
            "Kadokawa Pictures USA": "Кадокава Пикчерс США",
            "Valkyria": "Валькирия",
            "Kokusai Eigasha": "Кокусай Эйгася",
            "Toho": "Тохо",
            "Studio Kafka": "Студия Кафка",
            "Poly Animation": "Поли Анимейшн",
            "Taikong Works": "Тайконг Воркс",
            "Natural High": "Нэчурал Хай",
            "Atelier Tuki": "Ателье Туки",
            "Hot Bear": "Хот Бэар",
            "DiC Entertainment": "ДиСи Энтертейнмент",
            "Shenman Entertainment": "Шенман Энтертейнмент",
            "Uguisu Kobo": "Угуису Кобо",
            "100studio": "100студия",
            "Production +h.": "Продакшн +ч.",
            "Kojiro Shishido Animation Works": "Кодзиро Сисидо Анимейшн Воркс",
            "Anime Midstream": "Аниме Мидстрим",
            "yell": "Йелл",
            "Skouras": "Скорас",
            "Gentosha Comics": "Гентося Комикс",
            "KENMedia": "КЕНМедиа",
            "Central Park Media": "Сентрал Парк Медиа",
            "AIC PLUS+": "АИС ПЛАС+",
            "ACiD FiLM": "АСИД ФИЛМ",
            "Kinema Citrus": "Кинема Цитрус",
            "Picograph": "Пикограф",
            "Discovery": "Дискавери",
            "BaseSon": "БейсСан",
            "Critical Mass": "Критикал Масс",
            "Armor": "Армор",
            "Studio Pastoral": "Студия Пастораль",
            "Langmaor": "Лангмаор",
            "GODxDOG Production ": "ГОДхДОГ Продакшн",
            "Primastea": "Примастиа",
            "Magic Capsule": "Мэджик Капсул",
            "Yellow Film": "Йеллоу Филм",
            "Animeigo": "Анимейго",
            "Enoki Films": "Эноки Филмс",
            "Studio Pivote": "Студия Пивот",
            "Omnibus Japan": "Омнибус Джапан",
            "Nippon Shuppan Hanbai (Nippan) K.K.": "Ниппон Сюппан Ханбай (Ниппан) К.К.",
            "NHK Enterprises": "ЭнЭйчКей Энтерпрайзес",
            "MS Pictures": "МС Пикчерс",
            "Nippon Columbia": "Ниппон Коламбиа",
            "Animation 21": "Анимейшн 21",
            "Takara": "Такара",
            "DAX Production": "ДАКС Продакшн",
            "Five Ways": "Файв Вэйс",
            "Casio Entertainment": "Касио Энтертейнмент",
            "Kanaban Graphics": "Канабан Графикс",
            "Takeshobo": "Такэсёбо",
            "Seta Corporation": "Сета Корпорейшн",
            "Studio Bogey": "Студия Боги",
            "Rankin/Bass": "Рэнкин/Басс",
            "SamBakZa": "СамБакЗа",
            "Puzzle Animation Studio Limited": "Паззл Анимейшн Студия Лимитед",
            "Hoods Entertainment": "Худс Энтертейнмент",
            "Group Creato": "Груп Креато",
            "CCTV Animation Group": "ССиТиВи Анимейшн Груп",
            "Enterbrain": "Энтербрейн",
            "Epoch": "Эпок",
            "ATLUS": "АТЛАС",
            "TAKI Corporation": "ТАКИ Корпорейшн",
            "PrimeTime": "ПраймТайм",
            "Kawamoto Productions Ltd.": "Кавамото Продакшнс Лтд.",
            "Itasca Studio": "Итаска Студия",
            "The Village of Marchen": "Зе Вилладж оф Мархен",
            "Big West": "Биг Вест",
            "Kadokawa Pictures Japan": "Кадокава Пикчерс Джапан",
            "Chungeorahm Film": "Чунгорам Филм",
            "Encourage Films": "Энкуридж Филмс",
            "Cranberry": "Крэнберри",
            "Innocent Grey": "Инносент Грей",
            "NHK-BS2": "ЭнЭйчКей-БС2",
            "Oxybot": "Оксибот",
            "Film Workshop": "Филм Воркшоп",
            "Topcraft": "Топкрафт",
            "Sovat Theater": "Соват Театр",
            "PoRO": "ПоРО",
            "Tomoyasu Murata Company": "Томоясу Мурата Компани",
            "Heewon Entertainment": "Хивон Энтертейнмент",
            "UM Productions": "ЮЭм Продакшнс",
            "Iyasakadou Film": "Иясакадо Филм",
            "Union Cho": "Юнион Чо",
            "I.Toon": "Ай.Тун",
            "Sentai Filmworks": "Сентай Филмворкс",
            "Studio CANDY BOX": "Студия КЭНДИ БОКС",
            "Grasshoppa!": "Грассхоппа!",
            "Avaco Creative Studios": "Авако Криэйтив Студиос",
            "Amuse Pictures": "Амюс Пикчерс",
            "Yamato Works": "Ямато Воркс",
            "Tokuma Shoten": "Токума Сётэн",
            "KMMJ Studios": "КММДж Студиос",
            "Trick Block": "Трик Блок",
            "Indeprox": "Индепрокс",
            "Future Planet": "Фьючер Плэнет",
            "Animaruya": "Анимаруя",
            "Blue Eyes": "Блю Айс",
            "Tamura Shigeru Studio": "Тамура Сигеру Студия",
            "I-move": "Ай-мув",
            "Tsuchida Productions": "Цучида Продакшнс",
            "Grouper Productions": "Групер Продакшнс",
            "Asia-Do": "Азия-До",
            "Milky Cartoon": "Милки Картун",
            "Dream Force": "Дрим Форс",
            "ChuChu": "ЧуЧу",
            "ChiChinoya": "ЧиЧиноя",
            "Tokyo Media Connections": "Токио Медиа Коннекшнс",
            "Studio Unicorn": "Студия Юникорн",
            "T-Rex": "Ти-Рекс",
            "Amino": "Амино",
            "Studio Egg": "Студия Эгг",
            "Adult Source Media": "Адалт Сорс Медиа",
            "KBS": "КБС",
            "Studio Wombat": "Студия Вомбат",
            "Pastel": "Пастель",
            "Lemon Heart": "Лемон Харт",
            "Warner Bros.": "Ворнер Бразерс",
            "TAP": "ТАП",
            "AION Studio": "АЙОН Студия",
            "Panda Factory": "Панда Фэктори",
            "Telescreen": "Телескрин",
            "Purple Cow Studio Japan": "Пёрпл Кау Студия Джапан",
            "ElectromagneticWave": "ЭлектромагнетикВейв",
            "ACC Production": "АСС Продакшн",
            "International Digital Artist Inc.": "Интернэшнл Диджитал Артист Инк.",
            "Schoolzone": "Скулзоун",
            "Studio Eromatick": "Студия Эроматик",
            "Mary Jane": "Мэри Джейн",
            "AIC Takarazuka": "АИС Такаразука",
            "Filmlink International": "Филмлинк Интернэшнл",
            "Studio G-1Neo": "Студия Джи-1Нео",
            "Nichiei Agency": "Нитиэй Эйженси",
            "Office AO": "Офис АО",
            "Mad Box": "Мэд Бокс",
            "Procidis": "Просидис",
            "Kachidoki Studio": "Качидоки Студия",
            "Synergy Japan": "Синерджи Джапан",
            "MontBlanc Pictures": "МонБлан Пикчерс",
            "Studio Gokumi": "Студия Гокуми",
            "Studio Zero": "Студия Зеро",
            "AIC Build": "АИС Билд",
            "soket": "Сокет",
            "Studio Signal": "Студия Сигнал",
            "Studio Kuma": "Студия Кума",
            "ame pippin": "Аме Пиппин",
            "Minami Machi Bugyousho": "Минами Мати Бугёсё",
            "Jinnis Animation Studios": "Джиннис Анимейшн Студиос",
            "Bliss Pictures": "Блисс Пикчерс",
            "RTHK": "РТХК",
            "Hero Communication": "Хиро Коммуникейшн",
            "Postgal Workshop": "Постгал Воркшоп",
            "Maikaze": "Майказе",
            "Miramax Films": "Мирамакс Филмс",
            "HuaMei Animation": "ХуаМэй Анимейшн",
            "TiMi Studio Group": "ТиМи Студия Груп",
            "Cookie Jar Entertainment": "Куки Джар Энтертейнмент",
            "Venet": "Венет",
            "Beijing Sharaku Art Co.": "Бейджинг Сяраку Арт Ко.",
            "U/M/A/A Inc.": "Ю/М/А/А Инк.",
            "LandQ studios": "ЛэндКью Студиос",
            "Nitroplus": "Нитроплюс",
            "The Klock Worx": "Зе Клок Воркс",
            "OLE-M": "ОЛЕ-М",
            "Chaos Project": "Хаос Проджект",
            "M.S.C": "М.С.С",
            "flying DOG": "Флайинг ДОГ",
            "Hasbro": "Хасбро",
            "Digital Media Lab": "Диджитал Медиа Лаб",
            "Discotek": "Дискотек",
            "Nihon Falcom": "Нихон Фалком",
            "ING": "ИНГ",
            "Kamikaze Douga": "Камиказе Доуга",
            "Project No.9": "Проджект No.9",
            "GAGA Communications": "ГАГА Коммуникейшнс",
            "Ascension": "Асеншн",
            "Shogakukan Music & Digital Entertainment": "Сёгакукан Мьюзик Диджитал Энтертейнмент",
            "Ishikawa Pro": "Исикава Про",
            "The Berich": "Зе Берич",
            "Kino Production": "Кино Продакшн",
            "Kusama Art": "Кусама Арт",
            "DOGA Productions": "ДОГА Продакшнс",
            "Tokyo TV": "Токио ТВ",
            "Office Take Off": "Офис Тейк Офф",
            "Automatic Flowers Studio": "Автоматик Флауэрс Студия",
            "Marvel Entertainment": "Марвел Энтертейнмент",
            "TOKYOPOP": "ТОКИОПОП",
            "Shinwon Productions": "Синвон Продакшнс",
            "Studio MWP": "Студия МВП",
            "Anchor Bay Films": "Анкор Бэй Филмс",
            "TCJ": "ТСДжей",
            "Maiden Japan": "Мэйден Джапан",
            "Byakuya Shobo": "Бякуя Сёбо",
            "Horannabi": "Хораннаби",
            "Aniplex of America": "Аниплекс оф Америка",
            "Studio Take Off": "Студия Тейк Офф",
            "Moonstone Cherry": "Мунстоун Черри",
            "Studio Gram": "Студия Грам",
            "The Pokemon Company International": "Зе Покемон Компани Интернэшнл",
            "Atti Production": "Атти Продакшн",
            "team Yamahitsuji": "Тим Ямахицудзи",
            "Shanghai Animation Film Studio": "Шанхай Анимейшн Филм Студия",
            "7doc": "7док",
            "Twilight Town": "Твайлайт Таун",
            "J.T.P.P.": "Дж.Т.П.П.",
            "Chimu Jika Hatsuden": "Чиму Дзика Хацудэн",
            "Imagestone Inc.": "Имаджестоун Инк.",
            "Tsuburaya Productions": "Цубурая Продакшнс",
            "Nintendo of America": "Нинтендо оф Америка",
            "Universal Studios": "Юниверсал Студиос",
            "Fuji Video": "Фудзи Видео",
            "Wonder Kids": "Вондер Кидс",
            "Fairy Dust": "Фэйри Даст",
            "Collaboration Works": "Коллаборейшн Воркс",
            "Anpro": "Анпро",
            "SBS TV Production": "СБС ТВ Продакшн",
            "KAGAYA Studio": "КАГАЯ Студия",
            "Higa Brothers Production": "Хига Бразерс Продакшн",
            "Lapis": "Лапис",
            "Elevenarts": "Элевенартс",
            "N&G Production": "НДжи Продакшн",
            "SANZIGEN": "САНЗИГЕН",
            "Ultra Super Pictures": "Ультра Супер Пикчерс",
            "Imagica Digitalscape": "Имаджика Диджиталскейп",
            "Studio Saki Makura": "Студия Саки Макура",
            "Studio Deva Loka": "Студия Дева Лока",
            "Hobby Japan": "Хобби Джапан",
            "StudioRF Inc.": "СтудияРФ Инк.",
            "Crossphere": "Кросспхере",
            "Marvy Jack": "Марви Джек",
            "A4A Inc.": "А4А Инк.",
            "Obtain Future": "Обтейн Фьючер",
            "JapanAnime": "ДжапанАниме",
            "Katsudou-manga-kan": "Кацудо-манга-кан",
            "AT-2": "АТ-2",
            "STUDIO6'oN": "СТУДИЯ6оН",
            "Annapuru": "Аннапуру",
            "Arplants": "Арплантс",
            "IKK Room": "ИКК Рум",
            "Academy Productions": "Академи Продакшнс",
            "Romanov Films": "Романов Филмс",
            "Egg": "Эгг",
            "NYAV Post": "НИАВ Пост",
            "CLOCKUP": "КЛОКАП",
            "C2C": "Си2Си",
            "RAMS": "РАМС",
            "Sakura Production": "Сакура Продакшн",
            "Jormungand Production Partners": "Ёрмунганд Продакшн Партнерс",
            "Dream Creation": "Дрим Криэйшн",
            "Azumanga Daioh Production Committee": "Адзуманга Дайо Продакшн Комити",
            "Cospa": "Коспа",
            "SoftBank Creative Corp.": "СофтБанк Криэйтив Корп.",
            "Kimi To Boku Production Partners": "Кими то Боку Продакшн Партнерс",
            "H.O.T.D Production Committee": "Х.О.Т.Д Продакшн Комити",
            "Madoka Partners": "Мадока Партнерс",
            "Studio Sign": "Студия Сайн",
            "Acchi Kocchi Production Committee": "Акчи Кокчи Продакшн Комити",
            "Tasogare Otome×Amnesia Production Partners": "Тасогаре Отомэ×Амнезия Продакшн Партнерс",
            "Saki Achiga-hen Production Committee": "Саки Ачига-хэн Продакшн Комити",
            "Möbius Tone": "Мёбиус Тоун",
            "Hiiro No Kakera Production Committee": "Хиро но Какера Продакшн Комити",
            "Japan Aerospace Exploration Agency": "Джапан Аэроспейс Эксплорейшн Эйженси",
            "Trinity Sound": "Тринити Саунд",
            "Audio Highs": "Аудио Хайс",
            "Memory-Tech": "Мемори-Тек",
            "Hanokiwa Academy Student Council": "Ханокива Академи Студент Каунсил",
            "Sengoku Collection Production Committee": "Сэнгоку Коллекшн Продакшн Комити",
            "tsuritama partners": "Цуритама Партнерс",
            "Volks": "Фолькс",
            "Lucky Paradise": "Лаки Парадайс",
            "AKB0048 Production Committee": "АКБ0048 Продакшн Комити",
            "Right Gauge": "Райт Гейдж",
            "Dwango Music Entertainment": "Дванго Мьюзик Энтертейнмент",
            "chara-ani.com": "чара-ани.ком",
            "AC Create": "АС Криэйт",
            "My Melody Production Committee": "Май Мелоди Продакшн Комити",
            "Yomiuri Advertising": "Ёмиури Адвертайзинг",
            "Nexon": "Нексон",
            "ASCII Media Works": "АСКИИ Медиа Воркс",
            "Astarotte no Omocha! Production Committee": "Астароттэ но Омоча! Продакшн Комити",
            "Kadokawa Contents Gate": "Кадокава Контентс Гейт",
            "Bandai Namco Live Creative": "Бандай Намко Лайв Криэйтив",
            "NTT Docomo": "НТТ Докомо",
            "501st JOINT FIGHTER WING": "501-й ДЖОЙНТ ФАЙТЕР ВИНГ",
            "BS-TBS": "БС-ТБС",
            "Studio B&M": "Студия БМ",
            "Sankarea Production Committee": "Санкареа Продакшн Комити",
            "Natsuiro Kiseki Production Partners": "Нацуиро Кисэки Продакшн Партнерс",
            "feng": "Фэнг",
            "seikaisha": "Сэйкайся",
            "Notes": "Нотс",
            "Project Railgun": "Проджект Рейлган",
            "TMS-Kyokuchi": "ТМС-Кёкучи",
            "PPP": "ППП",
            "Delphi Sound": "Делфи Саунд",
            "12 Diary Holders": "12 Дайари Холдерс",
            "Dwango": "Дванго",
            "TV Tokyo Music": "ТВ Токио Мьюзик",
            "Studio Mausu": "Студия Маусу",
            "GANSIS": "ГАНСИС",
            "Hotline": "Хотлайн",
            "Hatsukoi Limited Production Committee": "Хацукои Лимитед Продакшн Комити",
            "Kiyosumi High School Mahjong Club": "Киёсуми Хай Скул Маджонг Клаб",
            "Raku High Student Council": "Раку Хай Студент Каунсил",
            "Inu x Boku SS Production Partners": "Ину х Боку СС Продакшн Партнерс",
            "Viki": "Вики",
            "Slowcurve": "Слоукёрв",
            "Sony Music Communications": "Сони Мьюзик Коммуникейшнс",
            "Project IS": "Проджект ИС",
            "Toshiba Entertainment": "Тосиба Энтертейнмент",
            "Project Eureka AO": "Проджект Эврика АО",
            "Cosmic Ray": "Космик Рэй",
            "Apollon": "Аполлон",
            "Pony Canyon Enterprises": "Пони Каньон Энтерпрайзес",
            "Marvelous AQL": "Марвелоус АКЛ",
            "PRA": "ПРА",
            "Sony Music Entertainment": "Сони Мьюзик Энтертейнмент",
            "Eye Move": "Ай Мув",
            "Sunny Side Up": "Санни Сайд Ап",
            "Miracle Robo": "Мирикл Робо",
            "Sakura Create": "Сакура Криэйт",
            "Majin": "Маджин",
            "Fuji Pacific Music Publishing": "Фудзи Пасифик Мьюзик Паблишинг",
            "Kyokuichi Tokyo Movie Shinsha": "Кёкуичи Токио Муви Синся",
            "Peter Pan Creation": "Питер Пан Криэйшн",
            "Bushiroad Inc.": "Бусироад Инк.",
            "Showgate": "Шоугейт",
            "AMG MUSIC": "АМГ МЬЮЗИК",
            "Studio NOA": "Студия НОА",
            "GKids": "ДжиКидс",
            "Advance Syakujii": "Адванс Сякудзии",
            "Happinet Pictures": "Хаппинет Пикчерс",
            "BIGLOBE": "БИГЛОУБ",
            "Dentsu Entertainment USA": "Денцу Энтертейнмент США",
            "Glams": "Гламс",
            "Yahoo! Japan": "Яху! Джапан",
            "Hobunsha": "Хобунся",
            "indigo line": "Индиго Лайн",
            "Momoi Planning": "Момои Планинг",
            "AIC Frontier": "АИС Фронтир",
            "Po10tial": "По10тиал",
            "Hang Zhou StarQ": "Хан Чжоу СтарКью",
            "SoftCel Pictures": "СофтСел Пикчерс",
            "EMI": "ИЭмАй",
            "WField": "ВФилд",
            "Next Media Animation": "Некст Медиа Анимейшн",
            "Cotton Doll": "Коттон Долл",
            "Trigger": "Триггер",
            "Lune Pictures": "Люн Пикчерс",
            "Amber Film Works": "Амбер Филм Воркс",
            "Jumondou": "Дзюмондо",
            "Studio Jack": "Студия Джек",
            "Otogi Production": "Отоги Продакшн",
            "Kyotoma": "Кётома",
            "UNLIMITED Partners": "АНЛИМИТЕД Партнерс",
            "Saki Zenkoku-hen Production Committee": "Саки Дзэнкоку-хэн Продакшн Комити",
            "Saban Entertainment": "Сабан Энтертейнмент",
            "BS Fuji": "БС Фудзи",
            "Project No Name": "Проджект Ноу Нейм",
            "Senran Kagura Partners": "Сэнран Кагура Партнерс",
            "Kazami Gakuen Koushiki Douga-bu": "Кадзами Гакуэн Косики Доуга-бу",
            "Kenji Studio": "Кендзи Студия",
            "Solid Vox": "Солид Вокс",
            "Charaction": "Чаракшн",
            "Triple X": "Трипл Икс",
            "SAMG Entertainment": "САМГ Энтертейнмент",
            "Devil Survivor 2 Animation Committee": "Девил Сурвайвор 2 Анимейшн Комити",
            "Index": "Индекс",
            "Shingeki no Kyojin Team": "Сингэки но Кёдзин Тим",
            "Flex Comics": "Флекс Комикс",
            "G-mode": "Джи-мод",
            "An DerCen": "Ан ДерЦен",
            "gimik": "Гимик",
            "Toranoana": "Тораноана",
            "Strawberry Meets Pictures": "Строберри Митс Пикчерс",
            "Cinema Tohoku": "Синема Тохоку",
            "Karaku": "Караку",
            "NOTTV": "НОТТВ",
            "G.P Entertainment": "Джи.Пи Энтертейнмент",
            "Tokyo Animation Film": "Токио Анимейшн Филм",
            "Tsubasa Entertainment": "Цубаса Энтертейнмент",
            "Studio Zealot": "Студия Зелот",
            "Tokuma Japan": "Токума Джапан",
            "AYCO": "АЙКО",
            "I.Gzwei": "И.Гцвай",
            "Studio Kelmadick": "Студия Келмадик",
            "Ryukyu Asahi Broadcasting": "Рюкю Асахи Бродкастинг",
            "Takahashi Studio": "Такахаси Студия",
            "Ankama": "Анкама",
            "Dynamic Planning": "Дайнамик Планинг",
            "CyberStep": "СайберСтеп",
            "Earth Star Entertainment": "Земля Стар Энтертейнмент",
            "Dibetagurashi Production Committee": "Дибетагураси Продакшн Комити",
            "Animation Do": "Анимейшн До",
            "Poncotan": "Понкотан",
            "Carp Studio": "Карп Студия",
            "NHK-BS1": "ЭнЭйчКей-БС1",
            "Studio Kaab": "Студия Кааб",
            "Tama Production": "Тама Продакшн",
            "Iwatobi High School Swimming Club": "Иватоби Хай Скул Свимминг Клаб",
            "Koichi Kikuchi": "Коичи Кикучи",
            "KKC Animation Production": "ККС Анимейшн Продакшн",
            "Manga Entertainment": "Манга Энтертейнмент",
            "teamKG": "ТимКГ",
            "Soft on Demand": "Софт он Деманд",
            "Watamote Production Committee": "Ватамотэ Продакшн Комити",
            "Studio Compile": "Студия Компайл",
            "Baramiri": "Барамири",
            "Mages": "Мейджес",
            "Crimson Star Media": "Кримсон Стар Медиа",
            "Pupa Production Committee": "Пупа Продакшн Комити",
            "Uchouten Kazoku Production Committee": "Утётэн Кадзоку Продакшн Комити",
            "Anime R": "Аниме Р",
            "Studio Liberty": "Студия Либерти",
            "Angelfish": "Энджелфиш",
            "Deck": "Дек",
            "SPEED": "СПИД",
            "BOOTLEG": "БУТЛЕГ",
            "Daiko": "Дайко",
            "P Productions": "Пи Продакшнс",
            "Creative Bridge": "Криэйтив Бридж",
            "Nihon Hoso Eigasha": "Нихон Хосо Эйгася",
            "Shou Fan Yu Shu Gongzuoshi": "Шоу Фан Ю Шу Гунцзоси",
            "Tesagure! Production Committee": "Тэсагурэ! Продакшн Комити",
            "Coamix": "Коамикс",
            "Maxell E-Cube": "Макселл И-Кьюб",
            "Kyodo Eiga": "Кёдо Эйга",
            "Kent House": "Кент Хаус",
            "Oddjob": "Одджоб",
            "Yanchester": "Янчестер",
            "Opera House": "Опера Хаус",
            "T.O Entertainment": "Т.О Энтертейнмент",
            "Liverpool": "Ливерпуль",
            "Himeyuri Alumnae Incorporated Foundation": "Химэюри Аламнай Инкорпорейтед Фаундейшн",
            "ASIA Documentary Productions": "АЗИЯ Докьюментари Продакшнс",
            "Milkshake": "Милкшейк",
            "BeeWorks": "БиВоркс",
            "Universal Radio Studio": "Юниверсал Радио Студия",
            "Mikakunin de Shinkoukei Production Committee": "Микакунин дэ Синкоукэй Продакшн Комити",
            "Japan Vistec": "Джапан Вистек",
            "DIVE II Entertainment": "ДАЙВ II Энтертейнмент",
            "Ai Addiction": "Ай Аддикшн",
            "Benesse Corporation": "Бенессэ Корпорейшн",
            "ZIZ": "ЗИЗ",
            "PoPoCo": "ПоПоКо",
            "Production IMS": "Продакшн ИМС",
            "Kyowa Film": "Кёва Филм",
            "Studio Nem": "Студия Нем",
            "Project Team Eikyuu Kikan": "Проджект Тим Эйкю Кикан",
            "Juvenage": "Джувенейдж",
            "Public & Basic": "Паблик Бэйсик",
            "Rising Force": "Райзинг Форс",
            "Studio Lotus": "Студия Лотус",
            "Magic Lantern Film": "Мэджик Лантерн Филм",
            "MMDGP": "ММДГП",
            "3xCube": "3хКьюб",
            "ZERO-A": "ЗЕРО-А",
            "Aikikaku Center": "Айкикаку Сентер",
            "Space Neko Company": "Спейс Неко Компани",
            "Dongwoo A&E": "Донгву АЕ",
            "Cosmos": "Космос",
            "Studio Zain": "Студия Зайн",
            "BreakBottle": "БрейкБоттл",
            "Namco Bandai Games": "Намко Бандай Геймс",
            "Lambert": "Ламберт",
            "TROYCA": "ТРОЙКА",
            "Gendai Production": "Гэндай Продакшн",
            "Rabbit Gate": "Рэббит Гейт",
            "Studio Korumi": "Студия Корюми",
            "1st PLACE": "1-й ПЛЭЙС",
            "Banpresto": "Банпресто",
            "Lucent Pictures Entertainment": "Люсент Пикчерс Энтертейнмент",
            "Tsubu Doll Production Committee": "Цубу Долл Продакшн Комити",
            "Zero-G Room": "Зеро-Джи Рум",
            "dwarf": "Дворф",
            "FOREST Hunting One": "ФОРЕСТ Хантинг Уан",
            "SEK Studios": "СЕК Студиос",
            "BEAM Entertainment": "БИМ Энтертейнмент",
            "TOHO animation": "ТОХО Анимейшн",
            "Shinano Kikaku": "Синано Кикаку",
            "Studio Cab": "Студия Кэб",
            "Sanrio Digital": "Санрио Диджитал",
            "Image Kei": "Имидж Кей",
            "Big Bang": "Биг Бэнг",
            "King Bee": "Кинг Би",
            "Allure": "Аллюр",
            "Flatiron Film Company": "Флэтайрон Филм Компани",
            "Aiti St.": "Айти Стрит",
            "Tri-Slash": "Трай-Слэш",
            "Nikkatsu Mukojima": "Никкацу Мукодзима",
            "Olive Studio": "Олив Студия",
            "Atelier Musa": "Ателье Муса",
            " Geijutsu Eigasha": "Гэйдзюцу Эйгася",
            "MK Pictures": "МК Пикчерс",
            "E&G Films": "ИДжи Филмс",
            "Ripple Film": "Рипл Филм",
            "Azeta Pictures": "Азета Пикчерс",
            "MooGoo": "МуГу",
            "Creators in Pack": "Криэйторс ин Пак",
            "L.": "Л.",
            "Ponycan USA": "Поникан США",
            "Studio 1st": "Студия 1-й",
            "Answer Studio": "Ансвер Студия",
            "Comic Umenohone": "Комик Уменохонэ",
            "Tokyo MX": "Токио МХ",
            "Mobcast": "Мобкаст",
            "Daiichi Kosho Co.": "Дайити Косё Ко.",
            "HeART-BIT": "Харт-Бит",
            "Teichiku Entertainment": "Тейчику Энтертейнмент",
            "Age Global Networks": "Эйдж Глобал Нетворкс",
            "Yamamura Animation": "Ямамура Анимейшн",
            "Studio GDW": "Студия ГДВ",
            "OLM Digital": "ОЛМ Диджитал",
            "Bandai Namco Games": "Бандай Намко Геймс",
            "I was a Ballerina": "Ай Воз э Баллерина",
            "Millepensee": "Милльпенсе",
            "KeyEast": "КейИст",
            "Evil Line Records": "Ивил Лайн Рекордс",
            "Sakura Color Film": "Сакура Колор Филм",
            "AniMan": "АниМан",
            "Studio Dadashow": "Студия Дадашоу",
            "AIR AGENCY": "АИР ЭЙЖЕНСИ",
            "Mistral Japan": "Мистраль Джапан",
            "Sola Digital Arts": "Сола Диджитал Артс",
            "Mirai Film": "Мирай Филм",
            "The National Film Center Japan": "Зе Нэшнл Филм Сентер Джапан",
            "Dentsu Eigasha Tokyo": "Денцу Эйгася Токио",
            "Studio Binzo": "Студия Бинзо",
            "Studio GOONEYS": "Студия ГУНИС",
            "Grooove": "Груув",
            "Glovision": "Гловижн",
            "Harappa": "Хараппа",
            "A-Real": "Эй-Реал",
            "Executive Decision": "Экзекьютив Дисижн",
            "ZIZ Entertainment (ZIZ)": "ЗИЗ Энтертейнмент (ЗИЗ)",
            "Studio Curtain": "Студия Кёртин",
            "Nakamura Production": "Накамура Продакшн",
            "Good Smile Company": "Гуд Смайл Компани",
            "Dynamo Pictures": "Дайнамо Пикчерс",
            "Sanjie Donghua": "Саньцзе Донхуа",
            "Studio! Cucuri": "Студия! Кукури",
            "Tencent Comic": "Тенсент Комик",
            "K-Factory": "Кей-Фэктори",
            "Sanctuary": "Сэнкчуэри",
            "Assez Finaud Fabric": "Ассе Фино Фабрик",
            "Osaka University of Arts": "Осака Юниверсити оф Артс",
            "Imagica West": "Имаджика Вест",
            "Buemon": "Буэмон",
            "Media Castle": "Медиа Касл",
            "Office DCI": "Офис ДСИ",
            "Arcturus": "Арктурус",
            "TC Entertainment": "ТС Энтертейнмент",
            "Avex Pictures": "Авекс Пикчерс",
            "Being": "Биинг",
            "10Gauge": "10Гейдж",
            "Q-Tec": "Кью-Тек",
            "Chrono Gear Creative": "Хроно Гир Криэйтив",
            "F.M.F": "Ф.М.Ф",
            "Pollyanna Graphics": "Поллианна Графикс",
            "KOO-KI": "КУУ-КИ",
            "TUBA": "ТУБА",
            "Romantica club !! ": "Романтика Клаб !!",
            "Studio Don Juan": "Студия Дон Хуан",
            "Marza Animation Planet": "Марза Анимейшн Планет",
            "Office Nobu": "Офис Нобу",
            "RoiVisual": "РуаВизуал",
            "PansonWorks": "ПансонВоркс",
            "Qualia Animation": "Квалиа Анимейшн",
            "Milestone Music Publishing": "Майлстоун Мьюзик Паблишинг",
            "AIC Classic": "АИС Классик",
            "Amuse": "Амюс",
            "Production GoodBook": "Продакшн ГудБук",
            "Joker Films": "Джокер Филмс",
            "Haoliners Animation": "Хаолинерс Анимейшн",
            "Shimogumi": "Симогуми",
            "Decovocal": "Дековокал",
            "Soeishinsha": "Соэйсинся",
            "Sugar Boy": "Шугар Бой",
            "EDGE": "ЭДЖ",
            "Issen": "Иссэн",
            "Hoods Drifters Studio": "Худс Дрифтерс Студия",
            "Darts": "Дартс",
            "Rabbit Machine": "Рэббит Машин",
            "Marine Entertainment": "Марин Энтертейнмент",
            "Shueisha": "Сюэйся",
            "Kazuki Production": "Кадзуки Продакшн",
            "G-Lam": "Джи-Лам",
            "Sprite Animation Studios": "Спрайт Анимейшн Студиос",
            "T.P.O": "Т.П.О",
            "Studio Jam": "Студия Джем",
            "domerica": "Домерика",
            "Piko Studio": "Пико Студия",
            "Studio Live": "Студия Лайв",
            "Blue Cat": "Блю Кэт",
            "Neft Film": "Нефт Филм",
            "W-Toon Studio": "Дабл-Тун Студия",
            "Kio Studio": "Кио Студия",
            "GARDEN LODGE": "ГАРДЕН ЛОДЖ",
            "Takara Tomy A.R.T.S": "Такара Томи А.Р.Т.С",
            "Ekura Animal": "Экура Анимал",
            "JCF": "ДжейСиЭф",
            "Ishimori Entertainment": "Исимори Энтертейнмент",
            "Mook DLE": "Мук ДЛЕ",
            "Egg Firm": "Эгг Фирм",
            "Arcs Create": "Аркс Криэйт",
            "REALTHING": "РЕАЛСИНГ",
            "Beijing Huihuang Animation Company": "Бейджинг Хуэйхуан Анимейшн Компани",
            "Coastline Animation Studio": "Костлайн Анимейшн Студия",
            "Bandai Namco Pictures": "Бандай Намко Пикчерс",
            "Anime Antenna Iinkai": "Аниме Антенна Инкай",
            "Hiro Media": "Хиро Медиа",
            "Odolttogi": "Одольттоги",
            "Shochiku Animation Institute": "Сётику Анимейшн Институт",
            "Studio Core": "Студия Кор",
            "Bouncy": "Баунси",
            "Ripromo": "Рипромо",
            "Studio Z5": "Студия З5",
            "Studio World": "Студия Ворлд",
            "Dongyang Animation": "Донъян Анимейшн",
            "Echoes": "Эхоуз",
            "Studio Ponoc": "Студия Понок",
            "Moss Design Unit": "Мосс Дизайн Юнит",
            "Image House": "Имидж Хаус",
            "Emon": "Эмон",
            "Flavors Soft": "Флейворс Софт",
            "Studio WHO": "Студия ВОЗ",
            "Namu Animation": "Наму Анимейшн",
            "Japan Taps": "Джапан Тапс",
            "Chippai": "Чиппай",
            "Dai Nippon Printing": "Дай Ниппон Принтинг",
            "TOCSIS": "ТОКСИС",
            "Team YokkyuFuman": "Тим ЁккюФуман",
            "XFLAG": "ЭКСФЛАГ",
            "Cygames": "Сайгеймс",
            "Kamio Japan": "Камио Джапан",
            "Will Palette": "Вилл Палетт",
            "Rockwell Eyes": "Роквелл Айс",
            "Tsukimidou": "Цукимидо",
            "Chiptune": "Чиптюн",
            "Circle Tribute": "Сёркл Трибьют",
            "Concept Films": "Концепт Филмс",
            "drop": "Дроп",
            "Creators Dot Com": "Криэйторс Дот Ком",
            "Karasfilms": "Карасфилмс",
            "Tencent Animation & Comics": "Тенсент Анимейшн Комикс",
            "Craftar Studios": "Крафтар Студиос",
            "Success Corp.": "Саксесс Корп.",
            "Stingray": "Стингрей",
            "Tengu Kobo": "Тэнгу Кобо",
            "Dai-Ichi Douga": "Дай-Ити Доуга",
            "Nishiki Studio": "Нисики Студия",
            "Imagineer": "Имаджинир",
            "Studio UGOKI": "Студия УГОКИ",
            "Studio Flad": "Студия Флад",
            "Studio Khronos": "Студия Хронос",
            "Beijing Rocen Digital": "Бейджинг Росен Диджитал",
            "Onionskin": "Оньонскин",
            "Anime Beans": "Аниме Бинс",
            "Studio OX": "Студия ОХ",
            "Minakata Laboratory": "Минаката Лаборатори",
            "Three-d": "Три-Ди",
            "Pops Inc.": "Попс Инк.",
            "Twin Engine": "Твин Энджин",
            "Studio CA": "Студия СА",
            "pH Studio": "пЭйч Студия",
            "D & D Pictures": "ДиДи Пикчерс",
            "Meruhensha": "Мэрухэнся",
            "Picante Circus": "Пиканте Сёркус",
            "Durandal": "Дюрандаль",
            "Geno Studio": "Гэно Студия",
            "Felix Film": "Феликс Филм",
            "Suiseisha": "Суйсэйся",
            "Piso Studio": "Писо Студия",
            "Studio Nanahoshi": "Студия Нанахоси",
            "Husio Studio": "Хусио Студия",
            "iDRAGONS Creative Studio": "айДРАГОНС Криэйтив Студия",
            "helo.inc": "Хело.инк",
            "KIZAWA Studio": "КИДЗАВА Студия",
            "KJJ Animation": "КДжДж Анимейшн",
            "EKACHI EPILKA": "ЭКАЧИ ЭПИЛКА",
            "Pb Animation": "ПиБи Анимейшн",
            "CUCURI": "КУКУРИ",
            "B&T": "БТ",
            "Light Chaser Animation Studios": "Лайт Чейсер Анимейшн Студиос",
            "Thundray": "Тандерэй",
            "CG Year": "СиДжи Йеар",
            "October Media": "Октобер Медиа",
            "Mili Pictures": "Мили Пикчерс",
            "Boyan Pictures": "Боян Пикчерс",
            "Studio Lings": "Студия Лингс",
            "Studio Hakk": "Студия Хакк",
            "Lapin Track": "Лапен Трак",
            "Lesprit": "Леспри",
            "Seven Stone Entertainment": "Севен Стоун Энтертейнмент",
            "GRIZZLY": "ГРИЗЗЛИ",
            "SELFISH": "СЕЛФИШ",
            "G-angle": "Джи-энгл",
            "33 Collective": "33 Коллектив",
            "Studio Ppuri": "Студия Ппури",
            "Urban Product": "Урбан Продакт",
            "TriF Studio": "ТрайФ Студия",
            "Shanghai Hippo Animation": "Шанхай Хиппо Анимейшн",
            "Guton Animation Studio": "Гутон Анимейшн Студия",
            "Tokyo Movie": "Токио Муви",
            "Square Enix Visual Works": "Сквер Эникс Визуал Воркс",
            "MASTER LIGHTS": "МАСТЕР ЛАЙТС",
            "Jumonji": "Дзюмондзи",
            "Saetta": "Саэтта",
            "monofilmo": "Монофильмо",
            "Magia Doraglier": "Магия Дораглиер",
            "Animation Planet": "Анимейшн Планет",
            "Grom": "Гром",
            "Aurum Production": "Аурум Продакшн",
            "Studio W.Baba": "Студия В.Баба",
            "P.I.C.S.": "П.И.С.С.",
            "Silver": "Силвер",
            "Dangun Pictures": "Дангун Пикчерс",
            "UWAN Pictures": "ЮВАН Пикчерс",
            "Brio Animation": "Брио Анимейшн",
            "CygamesPictures": "СайгеймсПикчерс",
            "Ankama Animations": "Анкама Анимейшнс",
            "Sega Interactive": "Сега Интерактив",
            "Imagica Imageworks": "Имаджика Имиджворкс",
            "Xing Yi Kai Chen": "Син И Кай Чен",
            "Studio Crocodile": "Студия Крокодайл",
            "Speed Inc.": "Спид Инк.",
            "Saigo no Shudan": "Сайго но Сюдан",
            "Liberty Animation Studio": "Либерти Анимейшн Студия",
            "MAT": "МАТ",
            "Idol": "Идол",
            "Samsara Animation Studio": "Самсара Анимейшн Студия",
            "Lide": "Лидэ",
            "Kate Arrow": "Кейт Эрроу",
            "Anon Pictures": "Анон Пикчерс",
            "ANIDO FILM": "АНИДО ФИЛМ",
            "Animation Staff Room": "Анимейшн Стафф Рум",
            "W+K Tokyo": "В+К Токио",
            "Welz Animation Studios": "Вельц Анимейшн Студиос",
            "StoryRiders Co. Ltd.": "СториРайдерс Ко. Лтд.",
            "Left Pocket Studio": "Лефт Покет Студия",
            "V-sign": "Ви-сайн",
            "Wolf Smoke Studio": "Вулф Смоук Студия",
            "Gainax Kyoto": "Гайнакс Киото",
            "HOTZIPANG": "ХОТЗИПАНГ",
            "Monster's Egg": "Монстерс Эгг",
            "Suna Kouhou": "Суна Кохо",
            "YURUPPE Inc.": "ЮРУППЭ Инк.",
            "Anima&Co.": "АнимаКо",
            "Drive": "Драйв",
            "Sparkly Key Animation Studio": "Спаркли Кей Анимейшн Студия",
            "Albacrow": "Альбакроу",
            "Peak Hunt": "Пик Хант",
            "Studio Hokiboshi": "Студия Хокибоши",
            "Tear Studio": "Тир Студия",
            "WHOPPERS": "ВОППЕРС",
            "LAN Studio": "ЛАН Студия",
            "Arch": "Арч",
            "maroyaka": "Марояка",
            "Konami animation": "Конами Анимейшн",
            "KWANED": "КВАНЕД",
            "CANOPUS": "КАНОПУС",
            "Volca": "Волка",
            "CinePix": "СинеПикс",
            "Yasuda Genshou Studio by Xenotoon": "Ясуда Гэнсё Студия бай Зенотун",
            "TYO Animations": "ТИО Анимейшнс",
            "Fever Creations": "Фивер Криэйшнс",
            "asread.": "АсРид.",
            "CGCG Studio": "СиДжиСиДжи Студия",
            "Marone": "Маронэ",
            "5 Inc.": "5 Инк.",
            "Studio Sota": "Студия Сота",
            "Frontier Engine": "Фронтир Энджин",
            "Blue bread": "Блю Брэд",
            "Ryuu M's": "Рюу Мс",
            "Tsubo Production": "Цубо Продакшн",
            "Ezòla": "Эзола",
            "Sublimation": "Саблимейшн",
            "Hurray!": "Хуррэй!",
            "StudioXD": "СтудияХД",
            "ONIRO": "ОНИРО",
            "studio YOG": "Студия ЙОГ",
            "Wonder Cat Animation": "Вондер Кэт Анимейшн",
            "GAV Video": "ГАВ Видео",
            "Mikimoto Production": "Микимото Продакшн",
            "MB planning": "МБ Планинг",
            "Griot Groove": "Гриот Грув",
            "Gonzo": "Гонзо",
            "Bones": "Боунс",
            "Bee Train": "Би Трейн",
            "Gainax": "Гайнакс",
            "Studio March": "Студия Марч",
            "Artland": "Артленд",
            "Fugaku": "Фугаку",
            "INTERFACEDOGS": "ИНТЕРФЕЙСДОГС",
            "Shykeumo Animation Studio": "Шайкеумо Анимейшн Студия",
            "Studio Polon": "Студия Полон",
            "EOTA": "ЭОТА",
            "Toei Advertising": "Тоэй Адвертайзинг",
            "ROLL2": "РОЛЛ2",
            "CMC Media": "СМС Медиа",
            "miHoYoAnime": "миХоЙоАниме",
            "Takun Manga Box": "Такун Манга Бокс",
            "J.C.Staff": "Джи Си Стафф",
            "Sunwoo Entertainment": "Санву Энтертейнмент",
            "Platinum Vision": "Платинум Вижн",
            "Picture Magic": "Пикчер Мэджик",
            "Studio 4°C": "Студия 4 градуса",
            "Taomee": "Таоми",
            "Ezo Kobo": "Эзо Кобо",
            "Sunrise Beyond": "Санрайз Бейонд",
            "Yokohama Animation Lab": "Йокохама Анимейшн Лаб",
            "Sony Pictures Entertainment": "Сони Пикчерс Энтертейнмент",
            "Xuni Ying Ye": "Сюни Ин Е",
            "Toei Animation": "Тоэй Анимейшн",
            "Seven Arcs Pictures": "Севен Аркс Пикчерс",
            "Studio Ghibli": "Студия Гибли",
            "AKOM": "АКОМ",
            "Revoroot": "Ревоут",
            "Big Pine Animation Studio": "Биг Пайн Анимейшн Студия",
            "Gear Studio": "Гир Студия",
            "Team OneOne": "Тим УанУан",
            "MOJO Animation": "МОДЖО Анимейшн",
            "Manaa Animation": "Манаа Анимейшн",
            "Blaze Studio": "Блейз Студия",
            "Wang Film Productions": "Ванг Филм Продакшнс",
            "D'ART Shtajio": "Д'АРТ Стаджио",
            "Grayscale Arts": "Грейскейл Артс",
            "Studio Placebo": "Студия Плацебо",
            "Kobito": "Кобито",
            "Teddy": "Тедди",
            "Studio Eight Color": "Студия Эйт Колор",
            "Studio Cockpit": "Студия Кокпит",
            "Miyajima Film": "Миядзима Филм",
            "InfiniOrange Animation Studio": "ИнфиниОрандж Анимейшн Студия",
            "Origin": "Ориджин",
            "Seasun Pictures": "СиСан Пикчерс",
            "Number 19 Animation": "Намбер 19 Анимейшн",
            "Igloo Studio": "Иглу Студия",
            "Nippon Animation": "Ниппон Анимейшн",
            "Studio Fantasia": "Студия Фантазия",
            "Manglobe": "Манглоб",
            "Creative House Pocket": "Криэйтив Хаус Покет",
            "Genco": "Генко",
            "Studio Comet": "Студия Комет",
            "Ajia-do": "Адзиа-до",
            "Fengyun Animation": "Фенъюн Анимейшн",
            "Arms": "Армс",
            "Satelight": "Сателайт",
            "ufotable": "юфотейбл",
            "Xebec": "Зебек",
            "Knack Productions": "Нак Продакшнс",
            "Pink Pineapple": "Пинк Пайнэппл",
            "D.A.S.T Corporation": "Д.А.С.Т Корпорейшн",
            "AZ Creative": "АЗ Криэйтив",
            "AIC": "АИС",
            "Mook Animation": "Мук Анимейшн",
            "Actas": "Актас",
            "OB Planning": "ОБ Планинг",
            "TNK": "ТНК",
            "Doga Kobo": "Дога Кобо",
            "HIDEHOMARE": "ХИДЕХОМАРЭ",
            "Super Normal Studio": "Супер Нормал Студия",
            "A-1 Pictures": "А-1 Пикчерс",
            "Nexus": "Нексус",
            "DR Movie": "ДР Муви",
            "production doA": "Продакшн ДоА",
            "Mushi Production": "Муши Продакшн",
            "TMS Entertainment": "ТМС Энтертейнмент",
            "Maruga Factory": "Маруга Фэктори",
            "Dimps": "Димпс",
            "uzupiyo Animation & Digital Works": "Узупиё Анимейшн Диджитал Воркс",
            "Wulifang": "Вулифанг",
            "Year Young Culture": "Еар Янг Калчер",
            "Artner": "Артнер",
            "APPP": "АППП",
            "Radix": "Радикс",
            "Studio Rikka": "Студия Рикка",
            "Group TAC": "Груп ТАК",
            "Studio Hibari": "Студия Хибари",
            "Triangle Staff": "Трайангл Стафф",
            "NHK": "ЭнЭйчКей",
            "SynergySP": "СинерджиСП",
            "Imagin": "Имаджин",
            "P.A. Works": "ПиЭй Воркс",
            "Pony Canyon": "Пони Каньон",
            "A.C.G.T.": "АСиДжиТи",
            "Production Reed": "Продакшн Рид",
            "Ashi Productions": "Аси Продакшнс",
            "Nelvana": "Нелвана",
            "Oh! Production": "О! Продакшн",
            "Shin-Ei Animation": "Син-Эй Анимейшн",
            "David Production": "Дэвид Продакшн",
            "Tezuka Productions": "Тэдзука Продакшнс",
            "Zexcs": "Зекс",
            "CoMix Wave Films": "КоМикс Вейв Филмс",
            "GoHands": "ГоХэндс",
            "White Fox": "Уайт Фокс",
            "Phoenix Entertainment": "Феникс Энтертейнмент",
            "Ordet": "Ордет",
            "Japan Home Video": "Джапан Хоум Видео",
            "Tele-Cartoon Japan": "Теле-Картун Джапан",
            "Asahi Production": "Асахи Продакшн",
            "Daewon Media": "Дэвон Медиа",
            "8bit": "8бит",
            "Palm Studio": "Палм Студия",
            "Lerche": "Лерхе",
            "Digital Frontier": "Диджитал Фронтир",
            "Knack Animation": "Нак Анимейшн",
            "MAPPA": "МАППА",
            "Cammot": "Каммот",
            "Fifth Avenue": "Фифс Авеню",
            "Wit Studio": "Вит Студия",
            "Graphinica": "Графиника",
            "Passione": "Пассионе",
            "NAZ": "НАЗ",
            "Polygon Pictures": "Полигон Пикчерс",
            "Gakken Eigakyoku": "Гаккен Эйгакёку",
            "Studio 3Hz": "Студия 3Гц",
            "Pierrot Plus": "Пьеро Плюс",
            "Brain's Base": "Брейнс Бейс",
            "Pie in the sky": "Пай ин зе Скай",
            "OLM": "ОЛМ",
            "Studio PuYUKAI": "Студия ПуЮКАЙ",
            "Qingkong Qian Li": "Цинконг Цянь Ли",
            "LIDENFILMS": "ЛИДЕНФИЛМС",
            "Studio Deen": "Студия Дин",
            "Science SARU": "Сайенс САРУ",
            "Usagi Ou": "Усаги О",
            "l-a-unch・BOX": "Эл-эй-анч・БОКС",
            "JJJOY Animation Studios": "ДЖДЖДЖОЙ Анимейшн Студиос",
            "Studio Elle": "Студия Эль",
            "Shaft": "Шафт",
            "Tatsunoko Production": "Тацуноко Продакшн",
            "Studio M2": "Студия М2",
            "Signal.MD": "Сигнал.МД",
            "Gallop": "Галлоп",
            "Studio Bingo": "Студия Бинго",
            "Reirs": "Рейрс",
            "Soigne": "Суанье",
            "Escape Velocity Animation": "Эскейп Велосити Анимейшн",
            "Office TakeOut": "Офис ТейкАут",
            "Le-joy Animation Studio": "Ле-джой Анимейшн Студия",
            "Public Enemies": "Паблик Энемис",
            "Shogakukan-Shueisha Productions": "Сёгакукан-Сюэйся Продакшнс",
            "Elias": "Элиас",
            "Ga-Crew": "Га-Крю",
            "Studio Outrigger": "Студия Аутриггер",
            "Geidai Animation": "Гейдай Анимейшн",
            "VROOOOM": "ВРУУУУМ",
            "Hero": "Хиро",
            "Sofix": "Софикс",
            "lxtl": "ЛхТл",
            "Digital Network Animation": "Диджитал Нетворк Анимейшн",
            "Madhouse": "Мэдхаус",
            "Anima": "Анима",
            "Directions": "Дирекшнс",
            "CloverWorks": "КловерВоркс",
            "Kadokawa Shoten": "Кадокава Сётэн",
            "GEMBA": "ГЕМБА",
            "Shuka": "Сюка",
            "Nut": "Нат",
            "NBCUniversal Entertainment": "ЭнБиСиЮниверсал Энтертейнмент",
            "Studio Moriken": "Студия Морикен",
            "ENGI": "ЭНГИ",
            "Maho Film": "Махо Филм",
            "Arvo Animation": "Арво Анимейшн",
            "Yaoyorozu": "Яоёродзу",
            "Bibury Animation Studios": "Бибери Анимейшн Студиос",
            "Children's Playground Entertainment": "Чилдренс Плейграунд Энтертейнмент",
            "Fenz": "Фенц",
            "Studio 9 Maiami": "Студия 9 Майами",
            "Milky Animation Label": "Милки Анимейшн Лейбл",
            "BYMENT": "БАЙМЕНТ",
            "Artmic": "Артмик",
            "Yomiuri Telecasting Corporation": "Ёмиури Телекастинг Корпорейшн",
            "Dazzling Star": "Дазлинг Стар",
            "Pancake": "Панкейк",
            "ASK Animation Studio": "АСК Анимейшн Студия",
            "DRAWIZ": "ДРАВИЗ",
            "Toho Interactive Animation": "Тохо Интерактив Анимейшн",
            "Yudubai Animation": "Юдубай Анимейшн",
            "Kaca Entertainment": "Кача Энтертейнмент",
            "Studio Signpost": "Студия Сайнпост",
            "Studio Colorido": "Студия Колоридо",
            "Spell Bound": "Спелл Баунд",
            "YHKT Entertainment": "УайЭйчКейТи Энтертейнмент",
            "Original Force": "Ориджинал Форс",
            "Congzhuo Animation": "Конгжуо Анимейшн",
            "Ai Si Animation Studio": "Ай Си Анимейшн Студия",
            "Taiko Studios": "Тайко Студиос",
            "Green Monster Team": "Грин Монстер Тим",
            "Making Animation": "Мейкинг Анимейшн",
            "Wei Chuang Jiang Xin": "Вэй Чуан Цзян Синь",
            "Code": "Код",
            "Life Work": "Лайф Ворк",
            "Painting Dream": "Пейнтинг Дрим",
            "DandeLion Animation Studio": "ДандеЛайон Анимейшн Студия",
            "Robot Communications": "Робот Коммуникейшнс",
            "Mokai Technology": "Мокай Технолоджи",
            "WAO World": "ВАО Ворлд",
            "HS Pictures Studio": "ЭйчЭс Пикчерс Студия",
            "Picona": "Пикона",
            "Sotsu": "Сотсу",
            "Plus Heads": "Плюс Хэдс",
            "Studio Coa": "Студия Коа",
            "Planet": "Плэнет",
            "Echo": "Эхо",
            "Tencent Penguin Pictures": "Тенсент Пенгуин Пикчерс",
            "Benlai Pictures": "Бенлай Пикчерс",
            "Ke Yue Xue Zi": "Кэ Юэ Сюэ Цзы",
            "Acca effe": "Акка Эффе",
            "Giga Production": "Гига Продакшн",
            "Wan Wei Mao Donghua": "Ван Вэй Мао Донхуа",
            "Kadokawa": "Кадокава",
            "Ether Kitten": "Этер Киттен",
            "Gosay Studio": "Госэй Студия",
            "PERIMETRON": "ПЕРИМЕТРОН",
            "LICO": "ЛИКО",
            "Red Dog Culture House": "Рэд Дог Калчер Хаус",
            "foodunited.": "ФудЮнайтед.",
            "Visual Flight": "Визуал Флайт",
            "Studio Shelter": "Студия Шелтер",
            "Djinn Power": "Джинн Пауэр",
            "Ten Tails Animation": "Тен Тейлс Анимейшн",
            "1IN": "1ИН",
            "DMM pictures": "ДММ Пикчерс",
            "Qianqi Animation": "Цяньци Анимейшн",
            "Alpha Animation": "Альфа Анимейшн",
            "TANOsim": "ТАНОсим",
            "LEVELS": "ЛЕВЕЛС",
            "LX Animation Studio": "ЛХ Анимейшн Студия",
            "Ekakiya": "Экакия",
            "TV Tokyo": "ТВ Токио",
            "Kitty Films": "Китти Филмс",
            "Viz Media": "Виз Медиа",
            "Tohokushinsha Film Corporation": "Тохокусинся Филм Корпорейшн",
            "TYO": "ТИО",
            "Durufix": "Дуруфикс",
            "Flat Studio": "Флэт Студия",
            "Maxilla": "Максилла",
            "Teatro Nishi Tokyo Studio": "Театро Ниси Токио Студия",
            "Suspenders": "Саспендерс",
            "Super Brain": "Супер Брейн",
            "Paper Animation": "Пейпер Анимейшн",
            "Original Dream": "Ориджинал Дрим",
            "Jichitai Anime": "Дзититай Аниме",
            "Reiki Eyes Animation": "Рейки Айс Анимейшн",
            "Creative Power Entertaining": "Криэйтив Пауэр Энтертейнинг",
            "Nikkatsu": "Никкацу",
            "Okuroto Noboru": "Окурото Нобору",
            "Magma Studio": "Магма Студия",
            "Oz Inc.": "Оз Инк.",
            "Mediabank": "Медиабанк",
            "CMAY Animation": "СМАЙ Анимейшн",
            "Bridge": "Бридж",
            "Gambit": "Гамбит",
            "Wawayu Animation": "Ваваю Анимейшн",
            "MORIE Inc.": "МОРИЭ Инк.",
            "Shirogumi": "Сирогуми",
            "HoriPro": "ХориПро",
            "L²Studio": "Л²Студия",
            "RG Animation Studios": "РГ Анимейшн Студиос",
            "Dancing CG Studio": "Дэнсинг СиДжи Студия",
            "ARECT": "АРЕКТ",
            "Asmik Ace": "Асмик Эйс",
            "FIREBUG": "ФАЙРБАГ",
            "Wolfsbane": "Вулфсбейн",
            "Nothing New": "Насинг Нью",
            "Connect": "Коннект",
            "C-Station": "Си-Стейшн",
            "Blade": "Блейд",
            "Orange": "Оранж",
            "EMT Squared": "ЕМТ Сквеад",
            "Lay-duce": "Лей-дюс",
            "Okuruto Noboru": "Окуруто Нобору",
            "Quebico": "Кебико",
            "Bakken Record": "Баккен Рекорд",
            "Studio A-CAT": "Студия А-КЭТ",
            "Studio Bind": "Студия Бинд",
            "Studio VOLN": "Студия ВОЛН",
            "Project Studio Q": "Проджект Студия Кью",
            "Studio Gohan": "Студия Гохан",
            "Transcendence Picture": "Трансенденс Пикчер",
            "HORNETS": "ХОРНЕТС",
            "Delight Animation": "Делайт Анимейшн",
            "Indivision": "Индивижн",
            "Spooky graphic": "Спуки График",
            "TthunDer Animation": "ТтанДер Анимейшн",
            "Studio Kingyoiro": "Студия Кингёиро",
            "Enishiya": "Энисия",
            "Planet Nemo Animation": "Плэнет Немо Анимейшн",
            "MMT Technology": "ММТ Технолоджи",
            "Trash Studio": "Трэш Студия",
            "XFLAG Pictures": "ЭКСФЛАГ Пикчерс",
            "Wise Guy": "Вайз Гай",
            "Rocen": "Росен",
            "Beijing Enlight Pictures": "Бейджинг Энлайт Пикчерс",
            "SIDO LIMITED": "СИДО ЛИМИТЕД",
            "Kitty Film Mitaka Studio": "Китти Филм Митака Студия",
            "LIDENFILMS Osaka Studio": "ЛИДЕНФИЛМС Осака Студия",
            "China Literature Limited": "Чайна Литературе Лимитед",
            "Dawn Animation": "Дон Анимейшн",
            "FILMONY": "ФИЛМОНИ",
            "B.CMAY PICTURES": "Б.СМАЙ ПИКЧЕРС",
            "Ruo Hong Culture": "Руо Хонг Калчер",
            "Flagship Line": "Флагшип Лайн",
            "Lingsanwu Animation": "Лингсанву Анимейшн",
            "Euluca Lab": "Эулука Лаб",
            "Qubic Pictures": "Кьюбик Пикчерс",
            "2:10 Animation": "2:10 Анимейшн",
            "Bellnox Films": "Беллнокс Филмс",
            "Soul Creative": "Соул Криэйтив",
            "Studio Animal": "Студия Анимал",
            "Studio Chizu": "Студия Чидзу",
            "Point Pictures": "Пойнт Пикчерс",
            "Mippei Eigeki Kiryuukan": "Миппэй Эйгэки Кирюкан",
            "XEBEC M2": "ЗЕБЕК М2",
            "Studio Guts": "Студия Гатс",
            "Network Kouenji Studio": "Нетворк Коэндзи Студия",
            "animate": "Анимейт",
            "Suzuki Mirano": "Судзуки Мирано",
            "BOMB! CUTE! BOMB!": "БОМБ! КЬЮТ! БОМБ!",
            "Nihikime no Dozeu": "Нихикимэ но Дозэу",
            "studio MOTHER": "Студия МАЗЕР",
            "Qzil.la": "Кзил.ла",
            "Tsumugi Akita Animation Lab": "Цумуги Акита Анимейшн Лаб",
            "Hololive Production": "Хололайв Продакшн",
            "Walt Disney Studios": "Уолт Дисней Студиос",
            "Drawing and Manual": "Дроинг энд Мануал",
            "Daiei Film Co. Ltd.": "Дайэй Филм Ко. Лтд.",
            "Sunrise": "Санрайз",
            "Motion Magic": "Моушн Мэджик",
            "Seven": "Севен",
            "Sparky Animation": "Спарки Анимейшн",
            "Pashmina": "Пашмина",
            "Marui Group": "Маруи Груп",
            "Gold Bear": "Голд Бэар",
            "Queen Bee": "Квин Би",
            "Story Effect": "Стори Эффект",
            "Studio Nuck": "Студия Нак",
            "EXNOA": "ЭКСНОА",
            "Manhoo Culture": "Манху Калчер",
            "TrioPen Studio": "ТриоПен Студия",
            "Noovo": "Нуво",
            "Nostalook": "Носталук",
            "Studio Jemi": "Студия Джеми",
            "LIDENFILMS Kyoto Studio": "ЛИДЕНФИЛМС Киото Студия",
            "Borutong": "Борутонг",
            "Fukushima Gaina": "Фукусима Гайна",
            "Paper Plane Animation Studio": "Пейпер Плейн Анимейшн Студия",
            "Gyorai Eizo Inc.": "Гёрай Эйзо Инк.",
            "studio hb": "Студия ЭйчБи",
            "Quad": "Квад",
            "New Generation": "Нью Дженерейшн",
            "ORADA COMPANY": "ОРАДА КОМПАНИ",
            "Maboroshi Koubou": "Мабороси Кобо",
            "Bibury Animation CG": "Бибери Анимейшн СиДжи",
            "Office No. 8": "Офис Но. 8",
            "Mousou Senka": "Мосо Сэнка",
            "Dream Entertainment": "Дрим Энтертейнмент",
            "Youmex": "Юмекс",
            "AXsiZ": "АКСсиЗ",
            "IMAGICA Lab.": "ИМАДЖИКА Лаб.",
            "Suoyi Technology": "Суои Технолоджи",
            "DMM.futureworks": "ДММ.фьючерворкс",
            "Zuiyo": "Дзуйё",
            "The Monk Studios": "Зе Монк Студиос",
            "AQUA ARIS": "АКВА АРИС",
            "Vasoon Animation": "Васун Анимейшн",
            "Kamitsubaki Studio": "Камицубаки Студия",
            "Gathering": "Гэзеринг",
            "81 Produce": "81 Произвести",
            "Live2D Creative Studio": "Лайв2Д Криэйтив Студия",
            "Steve N' Steven": "Стив эн Стивен",
            "NuTech Digital": "НуТек Диджитал",
            "Warner Music Japan": "Ворнер Мьюзик Джапан",
            "SJYNEXCUS": "СДЖАЙНЕКСКУС",
            "Fanworks": "Фанворкс",
            "ILCA": "ИЛКА",
            "Larx Entertainment": "Ларкс Энтертейнмент",
            "Woodpecker": "Вудпекер",
            "Telecom Animation Film": "Телеком Анимейшн Филм",
            "Tomovies": "Томувис",
            "Twilight Studio": "Твайлайт Студия",
            "Nur": "Нур",
            "Cyclone Graphics": "Циклон Графикс",
            "ZG-R": "ЗГ-Р",
            "Nippon Television Network Corporation": "Ниппон Телевижн Нетворк Корпорейшн",
            "WOWOW": "ВОУВОУ",
            "Kaname Productions": "Канамэ Продакшнс",
            "Wong Ping Animation Lab": "Вонг Пинг Анимейшн Лаб",
            "Comma Studio": "Комма Студия",
            "Studio Massket": "Студия Маскет",
            "OTOIRO": "ОТОИРО",
            "Passion Paint Animation": "Пассион Пейнт Анимейшн",
            "Cloud Hearts": "Клауд Хартс",
            "Angle": "Энгл",
            "Studio Mir": "Студия Мир",
            "Studio Ten Carat": "Студия Тен Карат",
            "Studio Boogie Nights": "Студия Буги Найтс",
            "Studio Nue": "Студия Нуэ",
            "Jinnan Studio": "Дзиннан Студия",
            "Studio Meditation With a Pencil": "Студия Медитейшн Виз э Пенсил",
            "Y.O.U.C": "Ю.О.Ю.С",
            "Yostar Pictures": "Йостар Пикчерс",
            "Soyuzmultfilm": "Союзмультфильм",
            "Sakura Motion Picture": "Сакура Моушн Пикчер",
            "HOTALL": "ХОТОЛЛ",
            "Kayac Animation": "Каяк Анимейшн",
            "Wuhu Studio": "Вуху Студия",
            "GLOWING & UNIT": "ГЛОУИНГ ЮНИТ",
            "Zhonghui Donghua": "Чжунхуэй Донхуа",
            "CLAP": "КЛАП",
            "Tomason": "Томасон",
            "Xanthus Media": "Ксантус Медиа",
            "OLM Team Yoshioka": "ОЛМ Тим Ёсиока",
            "Geneon Universal Entertainment": "Генеон Юниверсал Энтертейнмент",
            "Typhoon Graphics": "Тайфун Графикс",
            "Inugoya": "Инугоя",
            "Cafe de Jeilhouse": "Кафе де Джейлхаус",
            "Dentsu Inc.": "Денцу Инк.",
            "Studio Prokion": "Студия Прокион",
            "Magic Bus": "Мэджик Бас",
            "Production D.M.H": "Продакшн Д.М.Х",
            "Datama Film": "Датама Филм",
            "Sonsan Kikaku": "Сонсан Кикаку",
            "Cutie Bee": "Кьюти Би",
            "Studio Soul": "Студия Соул",
            "Melissa": "Мелисса",
            "Shinjukuza": "Синдзюкудза",
            "Meltdown": "Мелтдаун",
            "Lead": "Лид",
            "Shindeban Film": "Синдэбан Филм",
            "Shura": "Сюра",
            "Studio Ten": "Студия Тен",
            "Alfred Imageworks": "Альфред Имиджворкс",
            "PP Project": "ПП Проджект",
            "Kung Fu Frog Animation": "Кунг Фу Фрог Анимейшн",
            "Shion": "Сион",
            "Kigumi": "Кигуми",
            "Hayabusa Film": "Хаябуса Филм",
            "Planet Cartoon": "Плэнет Картун",
            "Flint Sugar": "Флинт Шугар",
            "Okumaza": "Окумаза",
            "P core": "Пи Кор",
            "Big Wing": "Биг Винг",
            "Potato House": "Потато Хаус",
            "Kantou Douga Kai": "Канто Доуга Кай",
            "Mouse": "Маус",
            "JOF": "ДЖОФ",
            "Tryforce": "Трайфорс",
            "Hanjin Animation": "Ханджин Анимейшн",
            "Scooter Films": "Скутер Филмс",
            "Fantawild Animation": "Фантавилд Анимейшн",
            "Gekkou": "Гекко",
            "Aurora Animation": "Аврора Анимейшн",
            "TypeZero": "ТипЗеро",
            "High Energy Studio": "Хай Энерджи Студия",
            "Chongzhuo Animation": "Чонгжуо Анимейшн",
            "bilibili": "Билибили",
            "Colored Pencil Animation Japan": "Колорд Пенсил Анимейшн Джапан",
            "Oriental Creative Color": "Ориентал Криэйтив Колор",
            "Joicy Studio": "Джойси Студия",
            "Bones Film": "Боунс Филм",
            "Qingxiang Culture": "Цинсян Калчер",
            "Happy Elements": "Хэппи Элементс",
            "E&H Production": "ИЭйч Продакшн",
            "Eshoya Honpo": "Эсёя Хонпо",
            "THINKR": "ТИНКР",
            "Da Huoniao Donghua": "Да Хуоняо Донхуа",
            "Qiyuan Yinghua": "Циюань Инхуа",
            "Kuri Jikken Manga Koubou": "Кури Дзиккен Манга Кобо",
            "trenova": "Тренова",
            "LB Commerce": "ЛБ Коммерс",
            "Au Praxinoscope": "О Праксиноскоп",
            "Gravity Well": "Гравити Велл",
            "Stereotype": "Стереотайп",
            "flag Co.": "Флаг Ко.",
            "UchuPeople": "УчуПипл",
            "Kinematics": "Кинематикс",
            "Geek Toys": "Гик Тойс",
            "Sharefun Studio": "Шеарфан Студия",
            "AHA Entertainment": "АХА Энтертейнмент",
            "Keyring": "Кейринг",
            "UKA": "ЮКА",
            "BUG FILMS": "БАГ ФИЛМС",
            "Studio A. Craft": "Студия А. Крафт",
            "DC Impression Vision": "ДС Импрешн Вижн",
            "Saber Project": "Сейбер Проджект",
            "Pmats9 studio": "Пматс9 Студия",
            "MoMo Production": "МоМо Продакшн",
            "Studio Gadget": "Студия Гаджет",
            "Sunflowers": "Санфлауэрс",
            "Colored Pencil Animation": "Колорд Пенсил Анимейшн",
            "6pucks": "6пакс",
            "SIGNIF": "СИГНИФ",
            "Cloud Art": "Клауд Арт",
            "Studio Blanc.": "Студия Блан.",
            "Big Firebird Culture": "Биг Файрбёрд Калчер",
            "cogitoworks": "КогитоВоркс",
            "studio NAGURI": "Студия НАГУРИ",
            "Bandai Namco Filmworks": "Бандай Намко Филмворкс",
            "Ice Butter": "Айс Баттер",
            "Steamworks": "Стимворкс",
            "Slow Studio": "Слоу Студия",
            "Atorie A.B.C.": "Аториэ А.Б.С.",
            "Guo Pengzi Studio": "Гуо Пенцзы Студия",
            "Kuai Ying Hu Yu": "Куай Ин Ху Ю",
            "d00r works": "д00р Воркс",
            "EDP graphic works": "ЕДП График Воркс",
            "Haneda xR Studio": "Ханеда хР Студия",
            "THINGS.": "ТИНГС.",
            "Voil": "Войл",
            "Goto Inc.": "Гото Инк.",
            "Studio Tumble": "Студия Тамбл",
            "Gunners": "Ганнерс",
            "Yamiken": "Ямикен",
            "Ishibashi Planning": "Исибаси Планинг",
            "Animation 501": "Анимейшн 501",
            "Studio Ranmaru": "Студия Ранмару",
            "Studio D-Volt": "Студия Д-Вольт",
            "Mirai Fusion": "Мирай Фьюжн",
            "Studio Jin": "Студия Джин",
            "Dyna Method": "Дайна Метод",
            "AIC Project": "АИС Проджект",
            "Delpic": "Делпик",
            "Eallin": "Эллин",
            "Studio Himalaya": "Студия Хималая",
            "Adonero": "Адонеро",
            "Central Animation Studio": "Сентрал Анимейшн Студия",
            "Nekonigashi Inc.": "Неконигаси Инк.",
            "HM Heros": "ЭйчЭм Хирос",
            "Makaria": "Макария",
            "Qiying Animation": "Циин Анимейшн",
            "Overlap": "Оверлэп",
            "Yinhe Changxing Culture": "Иньхэ Чансин Калчер",
            "Bigcat Studio": "Бигкэт Студия",
            "Tonari Animation": "Тонари Анимейшн",
            "Quyue Technology": "Цююэ Технолоджи",
            "TOHO animation STUDIO": "ТОХО Анимейшн СТУДИЯ",
            "Hananona Studio": "Хананона Студия",
            "PINE JAM": "ПАЙН ДЖЕМ",
            "Space-X": "Спейс-Икс",
            "Hand to Mouse.": "Хэнд ту Маус.",
            "Sumomo Film": "Сумомо Филм",
            "Miyu Productions": "Мию Продакшнс",
            "Garyuu Studio": "Гарю Студия",
            "Gone-zo": "Гон-зо",
            "Square Pictures": "Сквер Пикчерс",
            "ASTROBROS.": "АСТРОБРОС.",
            "Studio Gazelle": "Студия Газель",
            "C and R": "Си энд Ар",
            "Gonzino": "Гонзино",
            "Yuhodo": "Юходо",
            "J.K.I": "Дж.К.Ай",
            "General Entertainment": "Дженерал Энтертейнмент",
            "Enzo Animation": "Энзо Анимейшн",
            "Kyushu Network Animation": "Кюсю Нетворк Анимейшн",
            "Circus Production": "Сёркус Продакшн",
            "M&M": "ММ",
            "Project Team Muu": "Проджект Тим Муу",
            "AMGA": "АМГА",
            "Alice Production": "Алис Продакшн",
            "Onion Studio": "Оньон Студия",
            "Amarcord": "Амаркорд",
            "Ai Yume Mai": "Ай Юмэ Май",
            "TEC": "ТЕК",
            "C&S Production": "СиЭс Продакшн",
            "Twenty First": "Твенти Фёрст",
            "Blue Note": "Блю Ноут",
            "Makino Production": "Макино Продакшн",
            "924 Studio": "924 Студия",
            "Windy Studio": "Винди Студия",
            "Miota": "Миота",
            "BloomZ": "БлумЗет",
            "Imagica Infos": "Имаджика Инфос",
            "Ijigen Tokyo": "Идзигэн Токио",
            "HAL Film Maker": "ХАЛ Филм Мейкер",
            "Alke": "Алке",
            "EOEO System": "ЭОЭО Систем",
            "MI": "МИ",
            "Studio Moe": "Студия Моэ",
            "CELAVIE": "СЕЛАВИ",
            "aNCHOR": "ЭнКОР",
            "Project Team Sarah": "Проджект Тим Сара",
            "Kami Kukan": "Ками Кукан",
            "JM Animation": "ДжМ Анимейшн",
            "evg": "Евг",
            "New Deer": "Нью Деер",
            "CANON RECORDINGS": "КАНОН РЕКОРДИНГС",
            "Starry Cube": "Старри Кьюб",
            "Liyu Culture": "Лию Калчер",
            "Shengying Animation": "Шенъин Анимейшн",
            "Sankaku": "Санкаку",
            "Anime Tokyo": "Аниме Токио",
            "Hu Po Donghua": "Ху По Донхуа",
            "CHOCOLATE": "ЧОКОЛАТЕ",
            "Oyster": "Ойстер",
            "Hong Ying Animation": "Хонг Ин Анимейшн",
            "Studio Vandal": "Студия Вандал",
            "HuaDream": "ХуаДрим",
            "Shengguang Knight Culture": "Шенгуанг Найт Калчер",
            "Congrong Film": "Конгронг Филм",
            "Studio Add": "Студия Адд",
            "Caviar": "Кавиар",
            "NANON CREATIVE": "НАНОН КРИЭЙТИВ",
            "Contrail": "Контрейл",
            "HMCH": "ЭйчЭмСиЭйч",
            "ARCUS": "АРКУС",
            "Studio HUIT": "Студия УИТ",
            "Youku": "Юку",
            "Studio Matomo": "Студия Матомо",
            "Misogo Animation Studio": "Мисоко Анимейшн Студия",
            "Transistor Studio": "Транзистор Студия",
            "Shadow Steps": "Шэдоу Степс",
            "Xiaoming Taiji": "Сяомин Тайцзи",
            "Sasayuri": "Сасаюри",
            "Studio Artegg": "Студия Артегг",
            "Cloud Culture": "Клауд Калчер",
            "ANYZAC": "АНИЗАК",
            "Shikachan Studio": "Сикачан Студия",
            "Studio Lemon": "Студия Лемон",
            "Medo": "Медо",
            "Hezmon Animation": "Хезмон Анимейшн",
            "BUDDHA INC.": "БУДДА ИНК.",
            "Studio Easter": "Студия Истер",
            "Toyo Links Corporation": "Тойо Линкс Корпорейшн",
            "CompTown": "КомпТаун",
            "Xing Xing Donghua": "Син Син Донхуа",
            "Bebow": "Бебоу",
            "Production Wave": "Продакшн Вейв",
            "Village Studio": "Вилладж Студия",
            "ABJ COMPANY": "АБДж КОМПАНИ",
            "Tang Kirin Culture": "Танг Кирин Калчер",
            "Studio Yona": "Студия Йона",
            "Zero-G": "Зеро-Джи",
            "Hutoon Animation": "Хутун Анимейшн",
            "studio2 Animation Lab": "Студия2 Анимейшн Лаб",
            "Rock'n Roll Mountain": "Рок-н-Ролл Маунтин",
            "Studio Gale": "Студия Гейл",
            "Iconix Entertainment": "Иконикс Энтертейнмент",
            "Studio BAZOOKA": "Студия БАЗУКА",
            "Ocon Studio": "Окон Студия",
            "Studio Goindol": "Студия Гоиндол",
            "Brick Studio": "Брик Студия",
            "Pierrot Films": "Пьеро Филмс",
            "ORCEN": "ОРСЕН",
            "Infinity Animations": "Инфинити Анимейшнс",
            "studio ALBLE": "Студия АЛБЛЕ",
            "Particlefield": "Партиклфилд",
            "Flying Monkeys Production": "Флайинг Манкис Продакшн",
            "Studio Button": "Студия Баттон",
            "Studio KeepFire": "Студия КипФайр",
            "Foch Film": "Фоч Филм",
            "Tsumupapa": "Цумупапа",
            "Viewworks": "Вьюворкс",
            "Studio Barcelona": "Студия Барселона",
            "Tianshi Wenhua": "Тяньши Вэньхуа",
            "Watanabe Promotion": "Ватанабэ Промоушн",
            "Kachigarasu": "Качигарасу",
            "Crew-Cell": "Крю-Селл",
            "STUDIO 8 DOGS": "СТУДИЯ 8 ДОГС",
            "Seoul Movie": "Сеул Муви",
            "Youliao Studio": "Юлиао Студия",
            "Atelier Pontdarc": "Ателье Пондарк",
            "Zelico Film": "Зелико Филм",
            "Panda Tower Studio": "Панда Тауэр Студия",
            "WonderLand": "ВондерЛэнд",
            "AOI Pro.": "АОИ Про.",
            "SAFEHOUSE": "СЕЙФХАУС",
            "Alpha Group": "Альфа Груп",
            "Locus Corporation": "Локус Корпорейшн",
            "Aeonium": "Эониум",
            "Studio Clutch": "Студия Клатч",
            "Shuiniu Dongman": "Шуйню Донман",
            "LinQ": "ЛинКью",
            "Studio LEO": "Студия ЛЕО",
            "teevee graphics": "ТиВи Графикс",
            "Nagomi": "Нагоми",
            "KaKa Technology Studio": "КаКа Технолоджи Студия",
            "I&A": "АйЭй",
            "Kumarba": "Кумарба",
            "StealthWorks": "СтелсВоркс",
            "ILCASHIPS": "ИЛКАШИПС",
            "MAINCONCEPT": "МЕЙНКОНЦЕПТ",
            "Maru Animation": "Мару Анимейшн",
            "sugarsaltpepper": "ШугарСолтПеппер",
            "GARDEN Culture": "ГАРДЕН Калчер",
            "Animation Studio Wagumi": "Анимейшн Студия Вагуми",
            "No Side": "Ноу Сайд",
            "Axis": "Аксис",
            "Friendly Land": "Френдли Лэнд",
            "Fortes": "Фортес",
            "Front Wing": "Фронт Винг",
            "Raiose": "Райосэ",
            "Studio N": "Студия Н",
            "Cocktail Media": "Коктейл Медиа",
            "Mainichi Eigasha": "Майнити Эйгася",
            "717 Animation Studio": "717 Анимейшн Студия",
            "Production HASU": "Продакшн ХАСУ",
            "Digital Dream Studios": "Диджитал Дрим Студиос",
            "Laftel": "Лафтел",
            "BlueArc Animation Studios": "БлюАрк Анимейшн Студиос",
            "Painted Blade Studio": "Пейнтед Блейд Студия",
            "Nippon TV Douga": "Ниппон ТВ Доуга",
            "G&G Direction": "ДжиДжи Дирекшн",
            "Ginga Teikoku": "Гинга Тэйкоку",
            "Tokyo TV Douga": "Токио ТВ Доуга",
            "Imageworks Studio": "Имиджворкс Студия",
            "Saber Works": "Сейбер Воркс",
            "Lyrics": "Лирикс",
            "Buyuu": "Бую",
            "Sunny Gapen": "Санни Гапен",
            "Shadow Pond Studio": "Шэдоу Понд Студия",
            "Outline": "Аутлайн",
            "Sugata Creative & Design": "Сугата Криэйтив Дизайн",
            "Skydance Animation": "Скайданс Анимейшн",
            "Higashinaka Studio": "Хигасинака Студия",
            "LIGHTAIR Inc.": "ЛАЙТЭЙР Инк.",
            "R11R": "Р11Р",
            "Hanho Heung-Up": "Ханхо Хынг-Ап",
            "Pinkfong": "Пинкфонг",
            "Aurochs": "Аурокс",
            "Million Volt": "Миллион Вольт",
            "Studio Harutonari": "Студия Харутонари",
            "Kitchen Ltd.": "Китчен Лтд.",
            "Rhythmos": "Ритмос",
            "Manga Productions": "Манга Продакшнс",
            "STUDIOK110": "СТУДИЯК110",
            "FAB": "ФАБ",
            "Hifumi": "Хифуми",
            "CUEBiC": "КЬЮБИК",
            "Whatever": "Вотэвер",
            "3D": "3Д",
            "Studio Dotou": "Студия Дото",
            "OutSide Directors Company": "Аутсайд Директорс Компани",
            "Kassen": "Кассен",
            "Koinrush Studio": "Койнраш Студия",
            "MARK": "МАРК",
            "DEFT": "ДЕФТ",
            "Studio G7": "Студия Г7",
            "Stellar Pictures": "Стеллар Пикчерс",
            "Happy Toon": "Хэппи Тун",
            "Yumao Wenhua": "Юмао Вэньхуа",
            "G.H.Y. Culture & Media": "Джи.Эйч.Уай Калчер Медиа",
            "Long Zhi Gu Wenhua": "Лонг Чжи Гу Вэньхуа",
            "Yien Animation Studio": "Йен Анимейшн Студия",
            "D.ROCK-ART": "Д.РОК-АРТ",
            "Jiman Wenhua": "Дзиман Вэньхуа",
            "Zhou Ling Wenhua": "Чжоу Лин Вэньхуа",
            "Hei Chao Yinghua": "Хэй Чао Инхуа",
            "Chenghuang Yinghua": "Чэнхуан Инхуа",
            "Flying Fish Studio": "Флайинг Фиш Студия",
            "Bu Keneng de Shijie": "Бу Кенен де Шицзе",
            "Kid+Kid Animation Studio": "Кид+Кид Анимейшн Студия",
            "Lan Ying Yingshi": "Лан Ин Инши",
            "Tang Cai Zhaopin": "Тан Цай Чжаопин",
            "Tong Mingxuan Studio": "Тонг Минсюань Студия",
            "Honoo": "Хоноо",
            "S.o.K": "С.о.К",
            "INS Studio": "ИНС Студия",
            "asurafilm": "Асурафилм",
            "WWWave": "ВВВейв",
            "Climax Studio": "Климакс Студия",
            "Ziine Studio": "Зиине Студия",
            "Pepper Conpanna": "Пеппер Конпанна",
            "OSROCTION": "ОСРОКШН",
            "Nulls Design": "Наллс Дизайн",
            "Skyloong": "Скайлунг",
            "CALF": "КАЛФ",
            "Psyde Kick Studio": "Псайд Кик Студия",
            "animation studio42": "Анимейшн Студия42",
            "Gaina": "Гайна",
            "BENTEN Film": "БЕНТЕН Филм",
            "Funny Flux": "Фанни Флюкс",
            "Manpuku Jinja": "Манпуку Дзиндзя",
            "Kagome Company": "Кагоме Компани",
            "Nippon Ramayana Film": "Ниппон Рамаяна Филм",
            "Imagi": "Имаджи",
            "Studio Tron": "Студия Трон",
            "Triple A": "Трипл А",
            "Studio Pierrot": "Студия Пьеро",
            "Children's Corner": "Чилдренс Корнер",
            "Hoso Seisaku Doga": "Хосо Сейсаку Дога",
            "All Products": "Олл Продактс",
            "CEKAI": "СЕКАЙ",
            "studio maf": "Студия Маф",
            "Cue": "Кью",
            "Studio Maybe": "Студия Мейби",
            "mico.animation": "Мико.Анимейшн",
            "Studio Graph77": "Студия Граф77",
            "Studio KAI": "Студия КАЙ",
            "Toon Harbor Works": "Тун Харбор Воркс",
            "Nichicaline": "Ничикалайн",
            "Folium": "Фолиум",
            "Rouseact": "Роусэкт",
            "ABC Animation Studio": "ЭйБиСи Анимейшн Студия",
            "Finger and Toe": "Фингер энд Тоу",
            "Creatures": "Кричерс",
            "Gift-o'-Animation": "Гифт-о-Анимейшн",
            "Garage Film": "Гараж Филм",
            "studioDOT": "СтудияДОТ",
            "IKIF+": "ИКИФ+",
            "Studio BETTA": "Студия БЕТТА",
            "Atoonz": "Атунз",
            "Shenli Guangyin": "Шенли Гуанъин",
            "Guangzhou Liu Ling Yi": "Гуанчжоу Лю Лин И",
            "Tochka": "Точка",
            "Newon": "Невон",
            "Equator": "Экватор",
            "Project Team Argos": "Проджект Тим Аргос",
            "Office Academy": "Офис Академи",
            "StarLink": "СтарЛинк",
            "Aubeck": "Аубек",
            "Sunshine Corporation": "Саншайн Корпорейшн",
            "Teleimage": "Телеимидж",
            "Wako Production": "Вако Продакшн",
            "bushes": "Бушес",
            "TV Douga": "ТВ Доуга",
            "Lychee Time Media": "Лайчи Тайм Медиа",
            "Miyuki Production": "Миюки Продакшн",
            "B.COOL STUDIO": "Б.КУЛ СТУДИЯ",
            "Doraku": "Дораку",
            "Tsubasa Production": "Цубаса Продакшн",
            "Liliyabi Company Introduction": "Лилиаби Компани Интродакшн",
            "Honglu Technology": "Хунлу Технолоджи",
            "PAINTFREE": "ПЕЙНТФРИ",
            "Grass Jelly Studio": "Грасс Джелли Студия",
            "OCSTUDIO": "ОССТУДИЯ",
            "Atelier Peuplier": "Ателье Пёплие",
            "Gugenka": "Гугенка",
            "BIGBIGSUN": "БИГБИГСАН",
            "Aura Studio": "Аура Студия",
            "Nice Boat Animation": "Найс Боат Анимейшн",
            "WINSING ANIMATION": "ВИНСИНГ АНИМЕЙШН",
            "TRCARTOON": "ТРКАРТУН",
            "YNUO": "ЙНУО",
            "Studio Eek": "Студия Ик",
            "Da Chenger Gongzuoshi": "Да Чэнгэр Гунцзоси",
            "Akatsuki Media Studio": "Акацуки Медиа Студия",
            "Mofac Studio": "Мофак Студия",
            "Shen Fu Wenhua": "Шэнь Фу Вэньхуа",
            "A4works": "А4воркс",
            "Atra": "Атра",
            "Grass": "Грасс",
            "FuRyu Pictures": "ФуРю Пикчерс",
            "San Blas Animation": "Сан Блас Анимейшн",
            "Green Leaf Animation": "Грин Лиф Анимейшн",
            "Aisle": "Айл",
            "Bakkka": "Бакка",
            "Cannon Code": "Кэннон Код",
            "Hui Guang Gongzuoshi": "Хуэй Гуан Гунцзоси",
            "Daily Plan.net": "Дейли План.нет",
            "SO-DO Creative": "СО-ДО Криэйтив",
            "Computer Technique Group": "Компьютер Техник Груп",
            "coyote": "Койот",
            "Electric Circus": "Электрик Сёркус",
            "Studio Keel": "Студия Кил",
            "Moonseong Animation": "Мунсонг Анимейшн",
            "Haianxian Donghua Gongzuoshi": "Хайаньсянь Донхуа Гунцзоси",
            "Daicon Film": "Дайкон Филм",
            "Big Film Entertainment": "Биг Филм Энтертейнмент",
            "Cypic": "Сипик",
            "Studio AWAKE": "Студия АВАКЕ",
            "Studio Wrong": "Студия Ронг",
            "Ciwen Animation": "Цывэнь Анимейшн",
            "Kaihuang Donghua": "Кайхуан Донхуа",
            "You Hu Wenhua": "Ю Ху Вэньхуа",
            "Buzhi Dongman": "Бучжи Донман"
        };

        for (const [name, russian] of Object.entries(translations)) {
            await queryRunner.query(`UPDATE "studios" SET "russian" = $1 WHERE "name" = $2`, [russian, name]);
        }
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "studios" DROP COLUMN IF EXISTS "russian"`);
    }

}
